DO $$ BEGIN
  CREATE TYPE "PlanSource" AS ENUM ('DEFAULT', 'ADMIN', 'SUBSCRIPTION', 'INVOICE');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "planSource" "PlanSource" NOT NULL DEFAULT 'DEFAULT';
