export type MarketingLang = "ar" | "en";

const copy = {
  en: {
    lang: "en" as const,
    dir: "ltr" as const,
    brand: "Briefly NewsStream",
    navProduct: "Product",
    navCoverage: "Coverage",
    navDevelopers: "Developers",
    navPricing: "Pricing",
    navLive: "Live feed",
    navConsole: "Console",
    heroHeadline: "Market news API, Arabic-first.",
    heroLede:
      "Bilingual AR+EN articles, ranked by market impact, with community briefings and a permanent archive — built for developers.",
    ctaKey: "Get API key",
    ctaDocs: "View docs",
    proofLine: "Built for teams shipping market products across ~70 countries.",
    proofCountries: "~70 countries",
    proofLangs: "AR + EN",
    proofArchive: "Permanent archive",
    proofImpact: "Impact-ranked",
    sampleTitle: "A bilingual, impact-ranked response",
    sampleLede: "Every article ships with Arabic and English fields plus a market-impact score.",
    pillarsTitle: "What you actually get",
    pillarsLede: "Infrastructure for market intelligence — not another headline dump.",
    pillarBilingualTitle: "Arabic-first bilingual",
    pillarBilingualBody: "Every story is stored and served in Arabic and English. Arabic is the product default, English is a complete twin.",
    pillarImpactTitle: "Market-impact scoring",
    pillarImpactBody: "Rank the feed by market impact so teams read what moves markets, not noise.",
    pillarBriefingsTitle: "Community briefings",
    pillarBriefingsBody: "Ship short, audience-shaped briefings without building your own editorial stack.",
    pillarCoverageTitle: "One schema, ~70 countries",
    pillarCoverageBody: "Consistent country filters and payloads so products scale without per-market adapters.",
    pillarConsoleTitle: "Developer console",
    pillarConsoleBody: "Keys, explorer, scheduling, and docs in one console — not just a key generator page.",
    pillarArchiveTitle: "Permanent archive",
    pillarArchiveBody: "Query history without wondering what a free tier quietly deleted.",
    coverageTitle: "Coverage you can filter",
    coverageLede: "Country-level taxonomy, bilingual search, and category filters for gold, energy, finance, and markets.",
    useCasesTitle: "Built for real products",
    useCaseFintech: "Fintech & trading",
    useCaseFintechBody: "Surface impact-ranked market stories inside dashboards and alerts.",
    useCaseMedia: "Media & research",
    useCaseMediaBody: "Power bilingual desks and research workflows from one API.",
    useCaseAgents: "Agents & RAG",
    useCaseAgentsBody: "Ground models on structured AR+EN market context with stable schema.",
    useCaseApps: "Consumer apps",
    useCaseAppsBody: "Ship community briefings and localized market feeds without a newsroom.",
    trustTitle: "Live platform metrics",
    trustLede: "Counts from the running archive — not marketing theater.",
    metricArticles: "Articles indexed",
    metricCountries: "Countries covered",
    metricLanguages: "Languages",
    metricLanguagesValue: "AR + EN",
    pricingTitle: "Simple plans. Manual upgrades.",
    pricingLede: "No checkout yet — start free, request Pro or Enterprise from the console.",
    planFree: "Free",
    planFreePrice: "$0",
    planFreeBody: "Evaluate the API with bilingual responses, console access, and a daily request cap.",
    planPro: "Pro",
    planProPrice: "$60",
    planProPeriod: "/ month",
    planProBody: "Production quotas, full filters, community briefings, and commercial use. Upgraded by admin.",
    planEnterprise: "Enterprise",
    planEnterprisePrice: "Custom",
    planEnterpriseBody: "Volume, SLA, and support tailored to your team. Contact us to scope.",
    planCtaStart: "Sign up",
    planCtaContact: "Contact",
    faqTitle: "FAQ",
    faqLangQ: "Is Arabic really first-class?",
    faqLangA: "Yes. Articles are stored and returned with Arabic and English fields. The marketing site and API defaults lead with Arabic.",
    faqImpactQ: "What is market-impact scoring?",
    faqImpactA: "A ranking signal for market relevance so feeds prioritize stories that matter to gold, energy, finance, and related markets.",
    faqArchiveQ: "Do you delete historical articles?",
    faqArchiveA: "Indexed articles are kept in the permanent archive so you can query history reliably.",
    faqPayQ: "How do I upgrade to Pro?",
    faqPayA: "Create an account, then contact us or ask an admin to set your plan. Payment checkout ships later.",
    finalTitle: "Ship bilingual market news faster",
    finalLede: "Get an API key, explore the live feed, and open the developer console.",
    footerProduct: "Product",
    footerDocs: "API docs",
    footerConsole: "Console",
    footerNews: "Live feed",
    footerLegal: "Legal",
    footerPrivacy: "Privacy",
    footerTerms: "Terms",
    footerRights: "Briefly NewsStream. Market news infrastructure.",
  },
  ar: {
    lang: "ar" as const,
    dir: "rtl" as const,
    brand: "Briefly NewsStream",
    navProduct: "المنتج",
    navCoverage: "التغطية",
    navDevelopers: "للمطوّرين",
    navPricing: "الأسعار",
    navLive: "البث المباشر",
    navConsole: "اللوحة",
    heroHeadline: "واجهة أخبار الأسواق — العربية أولاً.",
    heroLede:
      "مقالات بالعربية والإنجليزية، مرتبة حسب أثر السوق، مع إحاطات مجتمعية وأرشيف دائم — للمطوّرين.",
    ctaKey: "احصل على مفتاح API",
    ctaDocs: "عرض التوثيق",
    proofLine: "مصمّم للفرق التي تبني منتجات أسواق عبر نحو ٧٠ دولة.",
    proofCountries: "نحو ٧٠ دولة",
    proofLangs: "عربية + إنجليزية",
    proofArchive: "أرشيف دائم",
    proofImpact: "مرتّب حسب الأثر",
    sampleTitle: "استجابة ثنائية اللغة ومرتّبة حسب الأثر",
    sampleLede: "كل مقال يصل بحقول عربية وإنجليزية مع درجة أثر السوق.",
    pillarsTitle: "ما الذي تحصل عليه فعلاً",
    pillarsLede: "بنية تحتية لذكاء الأسواق — لا مجرد تدفق عناوين.",
    pillarBilingualTitle: "ثنائية اللغة والعربية أولاً",
    pillarBilingualBody: "كل خبر يُخزَّن ويُقدَّم بالعربية والإنجليزية. العربية هي الافتراضي، والإنجليزية توأم كامل.",
    pillarImpactTitle: "تقييم أثر السوق",
    pillarImpactBody: "رتّب البث حسب أثر السوق ليقرأ الفريق ما يحرّك الأسواق لا الضوضاء.",
    pillarBriefingsTitle: "إحاطات مجتمعية",
    pillarBriefingsBody: "قدّم إحاطات قصيرة موجهة للجمهور دون بناء غرفة تحرير خاصة.",
    pillarCoverageTitle: "مخطط واحد، نحو ٧٠ دولة",
    pillarCoverageBody: "فلاتر دول واستجابات متسقة لتوسيع المنتج دون محوّلات لكل سوق.",
    pillarConsoleTitle: "لوحة المطوّر",
    pillarConsoleBody: "مفاتيح ومستكشف وجدولة وتوثيق في لوحة واحدة — لا مجرد صفحة توليد مفتاح.",
    pillarArchiveTitle: "أرشيف دائم",
    pillarArchiveBody: "استعلم عن التاريخ دون القلق مما حُذف بهدوء في خطة مجانية.",
    coverageTitle: "تغطية قابلة للتصفية",
    coverageLede: "تصنيف حسب الدولة، بحث ثنائي اللغة، وفلاتر للفئات: الذهب والطاقة والمال والأسواق.",
    useCasesTitle: "مبني لمنتجات حقيقية",
    useCaseFintech: "التقنية المالية والتداول",
    useCaseFintechBody: "اعرض أخبار الأسواق مرتّبة حسب الأثر داخل لوحات التنبيهات.",
    useCaseMedia: "الإعلام والبحث",
    useCaseMediaBody: "شغّل مكاتب ثنائية اللغة وسير عمل بحثية من واجهة واحدة.",
    useCaseAgents: "الوكلاء وRAG",
    useCaseAgentsBody: "أسند النماذج إلى سياق أسواق منظم بالعربية والإنجليزية.",
    useCaseApps: "تطبيقات المستهلك",
    useCaseAppsBody: "قدّم إحاطات مجتمعية وبثاً محلياً دون غرفة أخبار.",
    trustTitle: "مؤشرات المنصة الحية",
    trustLede: "أرقام من الأرشيف التشغيلي — لا مسرح تسويقي.",
    metricArticles: "مقالات مفهرسة",
    metricCountries: "دول مغطاة",
    metricLanguages: "اللغات",
    metricLanguagesValue: "عربية + إنجليزية",
    pricingTitle: "خطط بسيطة. ترقية يدوية.",
    pricingLede: "لا دفع إلكتروني بعد — ابدأ مجاناً واطلب Pro أو Enterprise من اللوحة.",
    planFree: "مجاني",
    planFreePrice: "$0",
    planFreeBody: "جرّب الواجهة باستجابات ثنائية اللغة ولوحة مطوّر وحد يومي للطلبات.",
    planPro: "Pro",
    planProPrice: "$60",
    planProPeriod: "/ شهر",
    planProBody: "حصص إنتاجية وفلاتر كاملة وإحاطات مجتمعية واستخدام تجاري. الترقية عبر المسؤول.",
    planEnterprise: "Enterprise",
    planEnterprisePrice: "مخصص",
    planEnterpriseBody: "حجم وSLA ودعم حسب فريقك. تواصل معنا لتحديد النطاق.",
    planCtaStart: "إنشاء حساب",
    planCtaContact: "تواصل",
    faqTitle: "أسئلة شائعة",
    faqLangQ: "هل العربية فعلاً بمستوى أول؟",
    faqLangA: "نعم. المقالات تُخزَّن وتُعاد بحقول عربية وإنجليزية. الموقع والافتراضيات يقودان بالعربية.",
    faqImpactQ: "ما تقييم أثر السوق؟",
    faqImpactA: "إشارة ترتيب لمدى صلة الخبر بالأسواق حتى يركز البث على ما يهم الذهب والطاقة والمال وما يرتبط بها.",
    faqArchiveQ: "هل تحذفون المقالات التاريخية؟",
    faqArchiveA: "المقالات المفهرسة تبقى في الأرشيف الدائم لاستعلام موثوق عن التاريخ.",
    faqPayQ: "كيف أترقى إلى Pro؟",
    faqPayA: "أنشئ حساباً ثم تواصل معنا أو اطلب من المسؤول تعيين خطتك. الدفع الإلكتروني لاحقاً.",
    finalTitle: "انشر أخبار الأسواق ثنائية اللغة أسرع",
    finalLede: "احصل على مفتاح API، استكشف البث المباشر، وافتح لوحة المطوّر.",
    footerProduct: "المنتج",
    footerDocs: "توثيق API",
    footerConsole: "اللوحة",
    footerNews: "البث المباشر",
    footerLegal: "قانوني",
    footerPrivacy: "الخصوصية",
    footerTerms: "الشروط",
    footerRights: "Briefly NewsStream. بنية تحتية لأخبار الأسواق.",
  },
} as const;

export function marketingCopy(lang: MarketingLang) {
  return copy[lang];
}
