export type MarketingLang = "ar" | "en";

const copy = {
  en: {
    lang: "en" as const,
    dir: "ltr" as const,
    brand: "Briefly NewsStream",
    navProduct: "Product",
    navCoverage: "Coverage",
    navDevelopers: "Developers",
    navPricing: "Pricing",
    navLive: "Live feed",
    navConsole: "Console",
    heroHeadline: "Market news as a stream.",
    heroLede:
      "Scored, bilingual, and built for global and regional markets.",
    heroLangSupport: "Arabic + English",
    heroSearchLabel: "Search the live feed",
    heroSearchPlaceholder: "Search gold, oil, rates…",
    heroSearchSubmit: "Search",
    ctaKey: "Get API key",
    ctaDocs: "View docs",
    proofLine: "Teams shipping market products across ~70 countries.",
    proofCountries: "~70 countries",
    proofLangs: "AR + EN",
    proofArchive: "Permanent archive",
    proofImpact: "Impact-ranked",
    conceptsTitle: "Product visuals for bilingual market teams",
    conceptsLede: "Concept visuals for Arabic-English products spanning regional and global coverage.",
    conceptDeskTitle: "Arabic-first by design",
    conceptDeskBody: "Bilingual badges and impact signals sit with the people shipping market products.",
    conceptStreamTitle: "News as a stream",
    conceptStreamBody: "Live bilingual coverage, impact scoring, and structured JSON in one product language.",
    conceptBentoTitle: "Coverage you can act on",
    conceptBentoBody: "Search, rank by impact, and brief communities without a newspaper layout.",
    sampleTitle: "A bilingual, impact-ranked response",
    sampleLede: "Every article ships with Arabic and English fields plus a market-impact score.",
    pillarsTitle: "What you actually get",
    pillarsLede: "Infrastructure for market intelligence. Structured feeds, not a headline dump.",
    pillarBilingualTitle: "Arabic-first bilingual",
    pillarBilingualBody: "Every story is stored and served in Arabic and English. Arabic is the product default, English is a complete twin.",
    pillarImpactTitle: "Market-impact scoring",
    pillarImpactBody: "Rank the feed by market impact so teams read what moves markets, not noise.",
    pillarBriefingsTitle: "Community briefings",
    pillarBriefingsBody: "Ship short, audience-shaped briefings without building your own editorial stack.",
    pillarCoverageTitle: "One schema, ~70 countries",
    pillarCoverageBody: "Consistent country filters and payloads so products scale across regional and global markets.",
    pillarConsoleTitle: "Developer console",
    pillarConsoleBody: "Keys, explorer, scheduling, and docs in one console. More than a key generator page.",
    pillarArchiveTitle: "Permanent archive",
    pillarArchiveBody: "Query history without wondering what a free tier quietly deleted.",
    coverageTitle: "Coverage you can filter",
    coverageLede: "Country-level taxonomy for regional and global markets, plus bilingual search and category filters.",
    useCasesTitle: "Where teams put it to work",
    useCaseFintech: "Fintech & trading",
    useCaseFintechBody: "Surface impact-ranked market stories inside dashboards and alerts.",
    useCaseMedia: "Media & research",
    useCaseMediaBody: "Power bilingual desks and research workflows from one API.",
    useCaseAgents: "Agents & RAG",
    useCaseAgentsBody: "Ground models on structured AR+EN market context with stable schema.",
    useCaseApps: "Consumer apps",
    useCaseAppsBody: "Ship community briefings and localized market feeds without a newsroom.",
    trustTitle: "Live platform metrics",
    trustLede: "Counts from the running archive.",
    metricArticles: "Articles indexed",
    metricCountries: "Countries covered",
    metricLanguages: "Languages",
    metricLanguagesValue: "AR + EN",
    pricingTitle: "Simple plans. Manual upgrades.",
    pricingLede: "No checkout yet - start free, request Pro or Enterprise from the console.",
    planFree: "Free",
    planFreePrice: "$0",
    planFreeBody: "Evaluate the API with bilingual responses, console access, and a daily request cap.",
    planPro: "Pro",
    planProPrice: "$60",
    planProPeriod: "/ month",
    planProBody: "Production quotas, full filters, community briefings, and commercial use. Upgraded by admin.",
    planEnterprise: "Enterprise",
    planEnterprisePrice: "Custom",
    planEnterpriseBody: "Volume, SLA, and support tailored to your team. Contact us to scope.",
    planCtaStart: "Sign up",
    planCtaContact: "Contact",
    skipToContent: "Skip to content",
    navAria: "Primary",
    langAria: "Language",
    menuOpen: "Menu",
    faqTitle: "FAQ",
    faqWhatQ: "What is Briefly NewsStream?",
    faqWhatA:
      "Briefly NewsStream is a bilingual Arabic-English market news API with impact scoring. It is built for global and regional markets, so developers get structured JSON, not a headline dump.",
    faqWhereQ: "Which regions and countries does it cover?",
    faqWhereA:
      "Coverage spans about 70 countries across regional and global markets, with bilingual search and category filters.",
    faqLangQ: "Is Arabic really first-class?",
    faqLangA:
      "Yes. Articles are stored and returned with Arabic and English fields. The product defaults lead with Arabic while English stays a complete twin.",
    faqImpactQ: "What is market-impact scoring?",
    faqImpactA:
      "Market-impact scoring is a ranking signal for market relevance so feeds prioritize stories that matter to gold, energy, finance, and related markets.",
    faqArchiveQ: "Do you delete historical articles?",
    faqArchiveA: "No. Indexed articles are kept in the permanent archive so you can query history reliably.",
    faqKeyQ: "How do I get an API key?",
    faqKeyA:
      "Sign up in the developer console, open API keys, create a key, then call the news endpoints or try the explorer. Free tier is available to evaluate.",
    faqPayQ: "How do I upgrade to Pro?",
    faqPayA: "Create an account, then contact us or ask an admin to set your plan. Payment checkout ships later.",
    finalTitle: "Ship bilingual market news faster",
    finalLede: "Get an API key, explore the live feed, and open the developer console.",
    footerProduct: "Product",
    footerDocs: "API docs",
    footerConsole: "Console",
    footerNews: "Live feed",
    footerLegal: "Legal",
    footerPrivacy: "Privacy",
    footerTerms: "Terms",
    footerRights: "Briefly NewsStream. Market news infrastructure for global and regional markets.",
  },
  ar: {
    lang: "ar" as const,
    dir: "rtl" as const,
    brand: "Briefly NewsStream",
    navProduct: "المنتج",
    navCoverage: "التغطية",
    navDevelopers: "للمطوّرين",
    navPricing: "الأسعار",
    navLive: "البث المباشر",
    navConsole: "اللوحة",
    heroHeadline: "أخبار الأسواق كبث مباشر.",
    heroLede:
      "مقيّمة، ثنائية اللغة، ومبنية للأسواق العالمية والإقليمية.",
    heroLangSupport: "العربية + الإنجليزية",
    heroSearchLabel: "ابحث في البث المباشر",
    heroSearchPlaceholder: "ابحث عن ذهب، نفط، فائدة…",
    heroSearchSubmit: "بحث",
    ctaKey: "احصل على مفتاح API",
    ctaDocs: "عرض التوثيق",
    proofLine: "لفرق تبني منتجات أسواق عبر نحو ٧٠ دولة.",
    proofCountries: "نحو ٧٠ دولة",
    proofLangs: "عربية + إنجليزية",
    proofArchive: "أرشيف دائم",
    proofImpact: "مرتّب حسب الأثر",
    conceptsTitle: "تصورات للمنتجات ثنائية اللغة",
    conceptsLede: "تصورات للمنتجات بالعربية والإنجليزية عبر الأسواق الإقليمية والعالمية.",
    conceptDeskTitle: "العربية أولاً بالتصميم",
    conceptDeskBody: "شارات ثنائية اللغة وإشارات الأثر مع الفرق التي تبني منتجات الأسواق.",
    conceptStreamTitle: "الأخبار كتيار",
    conceptStreamBody: "بث ثنائي اللغة مباشر، تقييم أثر، وJSON منظم بلغة منتج واحدة.",
    conceptBentoTitle: "تغطية قابلة للتنفيذ",
    conceptBentoBody: "ابحث، رتّب حسب الأثر، وقدّم إحاطات مجتمعية دون تخطيط صحيفة.",
    sampleTitle: "استجابة ثنائية اللغة ومرتّبة حسب الأثر",
    sampleLede: "كل مقال يصل بحقول عربية وإنجليزية مع درجة أثر السوق.",
    pillarsTitle: "ما الذي تحصل عليه فعلاً",
    pillarsLede: "بنية تحتية لذكاء الأسواق. بث منظم، لا مجرد تدفق عناوين.",
    pillarBilingualTitle: "ثنائية اللغة والعربية أولاً",
    pillarBilingualBody: "كل خبر يُخزَّن ويُقدَّم بالعربية والإنجليزية. العربية هي الافتراضي، والإنجليزية توأم كامل.",
    pillarImpactTitle: "تقييم أثر السوق",
    pillarImpactBody: "رتّب البث حسب أثر السوق ليقرأ الفريق ما يحرّك الأسواق لا الضوضاء.",
    pillarBriefingsTitle: "إحاطات مجتمعية",
    pillarBriefingsBody: "قدّم إحاطات قصيرة موجهة للجمهور دون بناء غرفة تحرير خاصة.",
    pillarCoverageTitle: "مخطط واحد، نحو ٧٠ دولة",
    pillarCoverageBody: "فلاتر دول واستجابات متسقة لتوسيع المنتج عبر الأسواق الإقليمية والعالمية.",
    pillarConsoleTitle: "لوحة المطوّر",
    pillarConsoleBody: "مفاتيح ومستكشف وجدولة وتوثيق في لوحة واحدة. أكثر من صفحة توليد مفتاح.",
    pillarArchiveTitle: "أرشيف دائم",
    pillarArchiveBody: "استعلم عن التاريخ دون القلق مما حُذف بهدوء في خطة مجانية.",
    coverageTitle: "تغطية قابلة للتصفية",
    coverageLede: "تصنيف حسب الدولة للأسواق الإقليمية والعالمية، مع بحث ثنائي اللغة وفلاتر للفئات.",
    useCasesTitle: "أين تستخدمها الفرق",
    useCaseFintech: "التقنية المالية والتداول",
    useCaseFintechBody: "اعرض أخبار الأسواق مرتّبة حسب الأثر داخل لوحات التنبيهات.",
    useCaseMedia: "الإعلام والبحث",
    useCaseMediaBody: "شغّل مكاتب ثنائية اللغة وسير عمل بحثية من واجهة واحدة.",
    useCaseAgents: "الوكلاء وRAG",
    useCaseAgentsBody: "أسند النماذج إلى سياق أسواق منظم بالعربية والإنجليزية.",
    useCaseApps: "تطبيقات المستهلك",
    useCaseAppsBody: "قدّم إحاطات مجتمعية وبثاً محلياً دون غرفة أخبار.",
    trustTitle: "مؤشرات المنصة الحية",
    trustLede: "أرقام من الأرشيف التشغيلي.",
    metricArticles: "مقالات مفهرسة",
    metricCountries: "دول مغطاة",
    metricLanguages: "اللغات",
    metricLanguagesValue: "عربية + إنجليزية",
    pricingTitle: "خطط بسيطة. ترقية يدوية.",
    pricingLede: "لا دفع إلكتروني بعد - ابدأ مجاناً واطلب Pro أو Enterprise من اللوحة.",
    planFree: "مجاني",
    planFreePrice: "$0",
    planFreeBody: "جرّب الواجهة باستجابات ثنائية اللغة ولوحة مطوّر وحد يومي للطلبات.",
    planPro: "Pro",
    planProPrice: "$60",
    planProPeriod: "/ شهر",
    planProBody: "حصص إنتاجية وفلاتر كاملة وإحاطات مجتمعية واستخدام تجاري. الترقية عبر المسؤول.",
    planEnterprise: "Enterprise",
    planEnterprisePrice: "مخصص",
    planEnterpriseBody: "حجم وSLA ودعم حسب فريقك. تواصل معنا لتحديد النطاق.",
    planCtaStart: "إنشاء حساب",
    planCtaContact: "تواصل",
    skipToContent: "انتقل إلى المحتوى",
    navAria: "التنقل الرئيسي",
    langAria: "اللغة",
    menuOpen: "القائمة",
    faqTitle: "أسئلة شائعة",
    faqWhatQ: "ما هو Briefly NewsStream؟",
    faqWhatA:
      "Briefly NewsStream واجهة برمجة لأخبار الأسواق بالعربية والإنجليزية مع تقييم أثر السوق. مبنية للأسواق العالمية والإقليمية، ليحصل المطوّرون على JSON منظم لا مجرد عناوين.",
    faqWhereQ: "ما المناطق والدول التي تغطيها؟",
    faqWhereA:
      "التغطية نحو ٧٠ دولة عبر الأسواق الإقليمية والعالمية، مع بحث ثنائي اللغة وفلاتر للفئات.",
    faqLangQ: "هل العربية فعلاً بمستوى أول؟",
    faqLangA:
      "نعم. المقالات تُخزَّن وتُعاد بحقول عربية وإنجليزية. الافتراضيات تقود بالعربية بينما تبقى الإنجليزية توأماً كاملاً.",
    faqImpactQ: "ما تقييم أثر السوق؟",
    faqImpactA:
      "تقييم أثر السوق إشارة ترتيب لمدى صلة الخبر بالأسواق حتى يركز البث على ما يهم الذهب والطاقة والمال وما يرتبط بها.",
    faqArchiveQ: "هل تحذفون المقالات التاريخية؟",
    faqArchiveA: "لا. المقالات المفهرسة تبقى في الأرشيف الدائم لاستعلام موثوق عن التاريخ.",
    faqKeyQ: "كيف أحصل على مفتاح API؟",
    faqKeyA:
      "سجّل في لوحة المطوّر، افتح مفاتيح الواجهة، أنشئ مفتاحاً، ثم استدعِ نقاط النهاية أو جرّب المستكشف. الخطة المجانية متاحة للتجربة.",
    faqPayQ: "كيف أترقى إلى Pro؟",
    faqPayA: "أنشئ حساباً ثم تواصل معنا أو اطلب من المسؤول تعيين خطتك. الدفع الإلكتروني لاحقاً.",
    finalTitle: "انشر أخبار الأسواق ثنائية اللغة أسرع",
    finalLede: "احصل على مفتاح API، استكشف البث المباشر، وافتح لوحة المطوّر.",
    footerProduct: "المنتج",
    footerDocs: "توثيق API",
    footerConsole: "اللوحة",
    footerNews: "البث المباشر",
    footerLegal: "قانوني",
    footerPrivacy: "الخصوصية",
    footerTerms: "الشروط",
    footerRights: "Briefly NewsStream. بنية تحتية لأخبار الأسواق العالمية والإقليمية.",
  },
} as const;

export function marketingCopy(lang: MarketingLang) {
  return copy[lang];
}
