export type MarketingLang = "ar" | "en";

const copy = {
  en: {
    lang: "en" as const,
    dir: "ltr" as const,
    brand: "Briefly NewsStream",
    productLine: "Market Intelligence API",
    navProduct: "Product",
    navHome: "Home",
    navDevelopers: "Developers",
    navPricing: "Pricing",
    navLive: "Briefing",
    navArchive: "Archive",
    navConsole: "Console",
    navLogin: "Log in",
    heroHeadline: "Know what news matters to markets",
    heroHeadlineEm: "",
    heroLede:
      "Structured market news with impact scores, ready for AI and financial products.",
    manifestoTitle:
      "Market intelligence API for products that need to understand what news matters to markets.",
    manifestoLede:
      "Real-time market news with impact scores and structured fields, ready for your product.",
    contrastOther: "Other news API providers = more news.",
    contrastBrand: "Briefly",
    contrastBrieflyBefore: " = more ",
    contrastBrieflyEm: "intelligence",
    contrastBrieflyAfter: " per news item.",
    definitionAnswer:
      "A market intelligence API delivers structured market news with impact scores and bilingual fields so products can decide which stories matter, not only list more headlines.",
    heroProof: "No credit card. 5 requests a day. Arabic and English.",
    heroLangSupport: "Arabic + English",
    heroSearchLabel: "Search live market data",
    heroSearchPlaceholder: "Search oil, rates, markets…",
    heroSearchSubmit: "Search",
    heroSearchClear: "Clear search",
    ctaKey: "Start free",
    navCta: "Start free",
    ctaDocs: "Open the API guide",
    ctaExploreApi: "Explore the API",
    ctaBriefing: "Open market data",
    sampleVisualTitle: "Global market news, ready to use",
    sampleCardKicker: "Global markets",
    sampleCardSource: "Reuters",
    sampleCardTitle: "Global equities hold as desks watch the next rate decision",
    sampleCardSummary: "Stock markets stay orderly while traders wait for the next move in policy.",
    sampleCardMeta: "Markets",
    sampleCardDate: "20 Aug 2026",
    sampleImpactLabel: "Impact",
    sampleImpactValue: "86",
    sampleImpactHigh: "High",
    sampleScoreTitle: "Story impact",
    scoreGold: "Metals impact",
    scoreRates: "Rates impact",
    scoreMarket: "Market impact",
    scoreUsd: "Dollar impact",
    scoreOil: "Oil impact",
    scoreGoldValue: "91",
    scoreRatesValue: "88",
    scoreMarketValue: "84",
    scoreUsdValue: "72",
    scoreOilValue: "61",
    scaleTitle: "Countries and markets you can filter.",
    scaleCountries: "100+",
    scaleCountriesHint: "Countries and markets",
    scaleRegions: "3",
    scaleRegionsHint: "Geographic regions",
    scaleCats: "7",
    scaleCatsHint: "Fixed market categories",
    scaleLangs: "2",
    scaleLangsHint: "Languages in the same response",
    demoTitle: "From a story to product-ready data",
    demoLede: "Call one endpoint. Get JSON your product can render.",
    demoQueryGold: "Market stories ranked by impact",
    demoQueryOil: "Oil and energy across covered markets",
    demoQueryRates: "Rate and finance headlines from the last 72 hours",
    demoGet: "GET",
    demoCopyHint: "Copy this shape into your client. Swap the sample for a console key.",
    demoJsonLabel: "Structured response",
    demoHtmlLabel: "What your product can render",
    demoDownload: "Open live market data",
    apiPath: "/api/v1/market-news?category=oil&region=global&sort=score",
    apiCloser: "Call one endpoint. Get JSON your product can render.",
    apiPoint1: "Filter with country and category",
    apiPoint2: "Rank by market impact",
    apiPoint3: "Try requests in the console",
    provideTitle: "News is everywhere. The signal is not.",
    provideLede:
      "Instead of flooding your product with thousands of headlines, Briefly gives you structured market data that shows what deserves attention.",
    provideLiveTitle: "Structured data",
    provideLiveBody: "Titles, summaries, categories, and geography in one usable shape.",
    provideArchiveTitle: "History you can query",
    provideArchiveBody: "Indexed stories stay. The live feed uses a 72-hour window. Both are available through the same API.",
    provideScoreTitle: "Unified data, ready to use",
    provideScoreBody:
      "Market news in a consistent, structured format you can drop straight into apps, products, and dashboards.",
    intelTitle: "Built for market intelligence",
    intelLede:
      "Turn market news into structured data your products can rank, filter, and act on.",
    intelCap1Title: "Market impact scoring",
    intelCap1Body:
      "Each story carries structured impact signals across rates, oil, metals, and the dollar so you can rank by what moves markets.",
    intelCap2Title: "Multi-market coverage",
    intelCap2Body:
      "Follow developments across equities, currencies, commodities, crypto, rates, and macroeconomic markets.",
    intelCap3Title: "AI-ready structured data",
    intelCap3Body:
      "Clean, consistent fields designed for applications, dashboards, AI agents, and automated workflows.",
    intelCap4Title: "Arabic and English fields",
    intelCap4Body:
      "Every story includes Arabic and English title and summary fields so products can serve bilingual desks from one response.",
    intelCap5Title: "Growing archive",
    intelCap5Body:
      "Indexed stories stay queryable. The live feed uses a 72-hour window; the archive keeps history available through the same API.",
    intelCap6Title: "Developer-first API",
    intelCap6Body:
      "Straightforward endpoints and predictable JSON make it easy to integrate Briefly into your products and workflows.",
    roadmapTitle: "Coming next",
    roadmapLede: "Shipped today: impact scores and bilingual fields. On the roadmap:",
    roadmapEventTitle: "Event detection",
    roadmapEventBody: "Cluster related stories into market events your product can subscribe to.",
    roadmapAssetTitle: "Asset mapping",
    roadmapAssetBody: "Link stories to tickers, commodities, and other assets when that layer ships.",
    flowTitle: "From news to actionable data",
    flowLede:
      "Briefly turns market developments into structured intelligence your products can process and use.",
    flowStep1Title: "Discover",
    flowStep1Body: "Relevant market developments are gathered and organized across financial and economic topics.",
    flowStep2Title: "Structure",
    flowStep2Body:
      "News is transformed into clean, consistent data with the context and metadata your application needs.",
    flowStep3Title: "Assess",
    flowStep3Body:
      "Stories are evaluated through market-relevant signals to help identify their potential significance.",
    flowStep4Title: "Deliver",
    flowStep4Body:
      "Access structured market intelligence through a simple API, ready for applications, dashboards, research tools, and AI workflows.",
    flowCloser: "One API. Structured market intelligence. Built for what comes next.",
    impactTitle: "Score each story by market.",
    impactLede:
      "Each story scores its effect on rates, oil, metals, and the dollar. Rank the feed by that impact, not only by what is newest.",
    capsTitle: "API features desks actually use",
    capIntegrateTitle: "REST, one header",
    capIntegrateBody: "Send X-API-Key and call /api/v1/market-news. A console explorer ships with the product.",
    capCountriesTitle: "100+ countries",
    capCountriesBody: "Filter with ISO codes such as US, AE, GB, DE, FR. Coverage is catalog-based, not an inflated source count.",
    capRegionsTitle: "Three market regions",
    capRegionsBody: "middle_east, america, and global. Use region when a desk thinks in blocs, not only countries.",
    capJsonTitle: "JSON, two languages",
    capJsonBody: "title and summary follow your request. arabic and english stay on the same story, with country, category, and scores.",
    capLangTitle: "Arabic first",
    capLangBody: "Arabic is the default. Ask for English when you need it. Both languages stay on every story.",
    capFreeTitle: "Evaluate on Free",
    capFreeBody: "Create a console account, mint a key, and stay within the daily limit. Request Pro at $70 a month from Billing.",
    queryTitle: "Search and filter the way the API works",
    queryLede: "Parameters below are the real query string. No invented operators.",
    queryTabSearch: "Keywords",
    queryTabRegion: "Region",
    queryTabPublishers: "Sources and categories",
    queryTabTime: "Timeline",
    querySearch1: "q searches Arabic or English. Example: oil prices or أسعار النفط.",
    querySearch2: "searchIn limits q to title, summary, or both.",
    querySearch3: "There is no boolean OR syntax. Use q, then tighten with country, category, or nationality.",
    querySearchCode: "q=oil&searchIn=title&sort=score",
    queryRegion1: "country takes ISO codes, comma-separated. Example: US,AE.",
    queryRegion2: "region is middle_east, america, or global.",
    queryRegion3: "nationality shapes community briefings for an audience, not the article country.",
    queryRegionCode: "country=US,AE&region=global",
    queryPub1: "category is a catalog code such as finance, oil, commodities, or markets.",
    queryPub2: "source is a source identifier, comma-separated.",
    queryPub3: "Combine source with category when a desk needs a tighter slice of the same feed.",
    queryPubCode: "category=oil&sort=score",
    queryTime1: "With no dates, the feed uses a 72-hour freshness window.",
    queryTime2: "date is a single calendar day and overrides that window.",
    queryTime3: "from and to are inclusive published-at bounds for archive queries.",
    queryTimeCode: "from=2026-08-01&to=2026-08-21&sort=date",
    sourcesTitle: "What the API returns",
    sourcesLede:
      "Market news organized for products: bilingual fields, country and category filters, and a live window plus archive.",
    sourcesRss: "Structured responses",
    sourcesGnews: "Bilingual fields",
    sourcesCatalog: "Country catalog",
    sourcesConsole: "Console keys and explorer",
    coverageTitle: "From one market to the world",
    coverageLede: "Filter by country or by market category.",
    coverageCta: "Open the briefing",
    coverageStatApi: "1",
    coverageStatApiHint: "API",
    coverageRegionLabel: "Market regions",
    coverageCatLabel: "Core categories",
    regionsMapTitle: "Coverage by region",
    regionsMapLede:
      "Middle East, the Americas, and global markets. Each card shows countries from that region.",
    regionMore: "more",
    regionCountHint: "countries",
    bilingualTitle: "Arabic and English in every story",
    bilingualLede:
      "Every story ships the headline and summary in Arabic and in English. title and summary follow the language you ask for. Arabic is the default.",
    bilingualArTitle: "Arabic",
    bilingualArBody: "arabic.title and arabic.summary are the Arabic headline and summary.",
    bilingualEnTitle: "English",
    bilingualEnBody: "english.title and english.summary are the English headline and summary.",
    useCasesTitle: "Who this feed is for",
    useCasesLede: "Build market news into trading platforms, media apps, AI agents, and research tools.",
    useCaseFintech: "Fintech and trading",
    useCaseFintechBody: "Put scored market news inside the product your desk already uses.",
    useCaseMedia: "Media",
    useCaseMediaBody: "Ship global market briefings in your app without standing up a newsroom.",
    useCaseAgents: "Artificial intelligence",
    useCaseAgentsBody: "Give agents structured market context instead of messy search results.",
    useCaseApps: "Research and analysis",
    useCaseAppsBody: "Query a lasting archive of classified, searchable news.",
    useCaseQuery: "Example query",
    trustTitle: "Coverage you can query",
    trustLede:
      "100+ countries. Arabic and English on every story. Filter by market and pull what your product needs.",
    trustPill: "Countries",
    trustCard1:
      "Live market news across 100+ countries, with Arabic and English on every story.",
    trustTryTitle: "Try the API",
    trustCard2: "Create an API key and explore the data from the developer console.",
    trustQueryHint: "Try a scored market query",
    trustQueryRun: "Run",
    metricCountries: "Countries",
    metricLanguages: "Languages",
    metricLanguagesValue: "2",
    metricWindow: "Live window",
    metricWindowValue: "72 hours",
    pricingTitle: "Start free. Scale when your product grows.",
    pricingLede: "Start free to try the API. Choose Pro for commercial use, or Enterprise at $150 a month.",
    planFree: "Free",
    planFreePrice: "$0",
    planFreeBody: "Evaluate the API with bilingual responses, console access, and a daily request cap.",
    planPro: "Pro",
    planProPrice: "$70",
    planProPeriod: "/ month",
    planProBody: "Production usage limits, full filters, and commercial use. Request it from Billing.",
    planEnterprise: "Enterprise",
    planEnterprisePrice: "$150",
    planEnterpriseBody: "Volume limits, priority support, and a published SLA. Request it from Billing. Free and Pro have no published SLA.",
    planCtaStart: "Start free",
    planCtaContact: "Contact us",
    skipToContent: "Skip to content",
    navAria: "Primary",
    langAria: "Language",
    menuOpen: "Menu",
    menuClose: "Close",
    footerHome: "Home",
    faqTitle: "FAQ",
    faqWhatQ: "What is Briefly NewsStream?",
    faqWhatA:
      "A market intelligence API for products. Each story has bilingual fields and impact scores you can filter and sort.",
    faqWhereQ: "Which regions and countries does it cover?",
    faqWhereA:
      "Filter by country or by region across the Middle East, Gulf, Europe, the Americas, and global markets. The coverage page lists every market.",
    faqLangQ: "Is Arabic really first-class?",
    faqLangA:
      "Yes. Arabic is the default. title and summary follow lang. arabic and english stay on every story.",
    faqImpactQ: "What is market-impact scoring?",
    faqImpactA:
      "Each story includes impact scores for rates, oil, metals, and the dollar. Rank the feed by market effect when newest-first is not enough.",
    faqArchiveQ: "Do you delete historical articles?",
    faqArchiveA:
      "Live Supabase keeps about 5 days for the briefing API (free-plan size). Optional Cloudflare R2 cold archive restores longer history on /archive — see docs/R2-CLOUDFLARE-SETUP.md.",
    faqKeyQ: "How do I start?",
    faqKeyA:
      "Create a console account, mint an API key, then call the news endpoints or try the explorer. Free is available to evaluate.",
    faqPayQ: "How do I upgrade to Pro?",
    faqPayA: "Create an account, start on Free, then request Pro from Billing. Payment is not live in the console yet.",
    finalTitle: "Get a free key and call the feed.",
    finalLede: "Create your key in the console, start on the Free plan, and request Pro at $70 a month from Billing.",
    footerProduct: "Product",
    footerDocs: "API docs",
    footerConsole: "Console",
    footerNews: "Briefing",
    footerArchive: "Archive",
    archiveKicker: "History",
    archiveTitle: "Market news archive",
    archiveLede:
      "Optional cold storage (Cloudflare R2) keeps stories beyond the live 5-day Supabase window. Configure it when you are ready — the live briefing works without it.",
    archiveNotConfigured: "Archive storage is not configured yet.",
    archiveEmpty: "No archived days yet. The first archive run will appear here.",
    archiveDayCount: (count: number) => `${count} stories`,
    archiveBackLive: "Back to live briefing",
    archiveDayTitle: (date: string) => `Archive · ${date}`,
    archiveDayLede: (count: number) => `${count} archived stories for this day.`,
    archiveEmptyDay: "No archived stories for this day.",
    archiveBackIndex: "All archive days",
    footerDevelopers: "Developers",
    footerResources: "Resources",
    footerLlms: "llms.txt",
    footerCompany: "Company",
    footerContact: "Contact",
    footerLegal: "Legal",
    footerPrivacy: "Privacy",
    footerTerms: "Terms",
    footerRights: "Market intelligence API for developers and digital products.",
    footerCopyright: "© 2026 Briefly NewsStream",
    footerMetaAria: "Legal and account",
    notFoundTitle: "Page not found",
    notFoundLede: "That address is not on this platform. Use the menu, search the briefing, or go home.",
    notFoundHome: "Back home",
  },
  ar: {
    lang: "ar" as const,
    dir: "rtl" as const,
    brand: "Briefly NewsStream",
    productLine: "واجهة ذكاء أسواق",
    navProduct: "المنتج",
    navHome: "الرئيسية",
    navDevelopers: "للمطوّرين",
    navPricing: "الأسعار",
    navLive: "الموجز",
    navArchive: "الأرشيف",
    navConsole: "اللوحة",
    navLogin: "تسجيل الدخول",
    heroHeadline: "اعرف أي خبر يهم الأسواق",
    heroHeadlineEm: "",
    heroLede:
      "أخبار أسواق منظمة بدرجة تأثير، جاهزة لمنتجات الذكاء الاصطناعي والمالية.",
    manifestoTitle:
      "واجهة ذكاء أسواق للمنتجات التي تحتاج أن تفهم أي خبر يهم الأسواق.",
    manifestoLede: "أخبار أسواق لحظية بدرجة تأثير وحقول منظمة جاهزة لمنتجك.",
    contrastOther: "واجهات الأخبار الأخرى = المزيد من العناوين.",
    contrastBrand: "Briefly",
    contrastBrieflyBefore: " = ",
    contrastBrieflyEm: "ذكاء أعلى",
    contrastBrieflyAfter: " لكل خبر.",
    definitionAnswer:
      "واجهة ذكاء الأسواق تقدّم أخبار أسواق منظمة بدرجات أثر وحقول ثنائية اللغة، حتى تقرر المنتجات أي خبر يستحق الانتباه، لا أن تعرض المزيد من العناوين فقط.",
    heroProof: "لا تحتاج إلى بطاقة ائتمانية. 5 طلبات يومياً. دعم العربية والإنجليزية.",
    heroLangSupport: "العربية والإنجليزية",
    heroSearchLabel: "ابحث في بيانات الأسواق",
    heroSearchPlaceholder: "ابحث عن نفط، فائدة، أسواق…",
    heroSearchSubmit: "بحث",
    heroSearchClear: "مسح البحث",
    ctaKey: "ابدأ مجاناً",
    navCta: "ابدأ مجاناً",
    ctaDocs: "اقرأ دليل API",
    ctaExploreApi: "استكشف واجهة API",
    ctaBriefing: "افتح بيانات الأسواق",
    sampleVisualTitle: "أخبار الأسواق العالمية، جاهزة للاستخدام",
    sampleCardKicker: "الأسواق العالمية",
    sampleCardSource: "Reuters",
    sampleCardTitle: "أسواق الأسهم العالمية تتماسك مع ترقّب قرارات الفائدة",
    sampleCardSummary: "الأسواق تبقى منتظمة بينما ينتظر المتعاملون الخطوة التالية في السياسة النقدية.",
    sampleCardMeta: "الأسواق",
    sampleCardDate: "20 أغسطس 2026",
    sampleImpactLabel: "أثر",
    sampleImpactValue: "86",
    sampleImpactHigh: "مرتفع",
    sampleScoreTitle: "أثر الخبر",
    scoreGold: "أثر المعادن",
    scoreRates: "أثر الفائدة",
    scoreMarket: "أثر الأسواق",
    scoreUsd: "أثر الدولار",
    scoreOil: "أثر النفط",
    scoreGoldValue: "91",
    scoreRatesValue: "88",
    scoreMarketValue: "84",
    scoreUsdValue: "72",
    scoreOilValue: "61",
    scaleTitle: "الدول والأسواق التي تغطيها.",
    scaleCountries: "100+",
    scaleCountriesHint: "دولة وأسواق",
    scaleRegions: "3",
    scaleRegionsHint: "نطاقات جغرافية",
    scaleCats: "7",
    scaleCatsHint: "فئات سوق ثابتة",
    scaleLangs: "2",
    scaleLangsHint: "لغتان في نفس الاستجابة",
    demoTitle: "من الخبر إلى بيانات جاهزة لمنتجك",
    demoLede: "استدعِ نقطة نهاية واحدة. احصل على JSON يعرضه منتجك.",
    demoQueryGold: "أخبار الأسواق مرتّبة حسب الأثر",
    demoQueryOil: "النفط والطاقة عبر الأسواق المغطاة",
    demoQueryRates: "عناوين الفائدة والمال خلال 72 ساعة",
    demoGet: "GET",
    demoCopyHint: "انسخ هذا الشكل إلى عميلك. استبدل النموذج بمفتاح من اللوحة.",
    demoJsonLabel: "استجابة منظمة",
    demoHtmlLabel: "ما يمكن لمنتجك عرضه",
    demoDownload: "افتح بيانات الأسواق الحية",
    apiPath: "/api/v1/market-news?category=oil&region=global&sort=score",
    apiCloser: "استدعِ نقطة نهاية واحدة. احصل على JSON يعرضه منتجك.",
    apiPoint1: "صفِّ بالدولة والفئة",
    apiPoint2: "رتّب حسب أثر السوق",
    apiPoint3: "جرّب الطلبات من اللوحة",
    provideTitle: "الأخبار متاحة في كل مكان. الإشارة المهمة ليست كذلك.",
    provideLede:
      "بدلًا من إغراق منتجك بآلاف العناوين، تمنحك Briefly بيانات سوق منظمة تساعدك على معرفة ما يستحق الانتباه.",
    provideLiveTitle: "بيانات منظمة",
    provideLiveBody: "عناوين وملخصات وتصنيفات ومعلومات جغرافية في صيغة واحدة جاهزة للاستخدام.",
    provideArchiveTitle: "تاريخ يمكن استعلامه",
    provideArchiveBody: "القصص المفهرسة تبقى. الموجز المباشر نافذة 72 ساعة. كلاهما متاح عبر الواجهة نفسها.",
    provideScoreTitle: "بيانات موحّدة، جاهزة للاستخدام",
    provideScoreBody:
      "أخبار الأسواق في صيغة منظمة ومتسقة، لتتمكن من دمجها مباشرة في تطبيقاتك ومنتجاتك ولوحات المعلومات.",
    intelTitle: "مصمّم لذكاء الأسواق",
    intelLede:
      "حوّل أخبار الأسواق إلى بيانات منظمة يمكن لمنتجاتك ترتيبها وتصفيتها والتصرف بناءً عليها.",
    intelCap1Title: "قياس أثر السوق",
    intelCap1Body:
      "كل خبر يحمل إشارات أثر منظمة على الفائدة والنفط والمعادن والدولار، لترتّب حسب ما يحرّك الأسواق.",
    intelCap2Title: "تغطية متعددة للأسواق",
    intelCap2Body:
      "تابع أبرز التطورات في الأسهم والعملات والسلع والأصول الرقمية وأسواق الفائدة والاقتصاد الكلي.",
    intelCap3Title: "بيانات جاهزة للذكاء الاصطناعي",
    intelCap3Body:
      "حقول نظيفة ومتسقة للتطبيقات ولوحات المعلومات والوكلاء الذكيين وسير العمل المؤتمت.",
    intelCap4Title: "حقول عربية وإنجليزية",
    intelCap4Body:
      "كل خبر يتضمن عنواناً وملخصاً بالعربية والإنجليزية، لتخدم المنتجات مكاتب ثنائية اللغة من استجابة واحدة.",
    intelCap5Title: "أرشيف متنامٍ",
    intelCap5Body:
      "القصص المفهرسة تبقى قابلة للاستعلام. الموجز المباشر نافذة 72 ساعة، والأرشيف يحفظ التاريخ عبر الواجهة نفسها.",
    intelCap6Title: "واجهة للمطوّرين أولاً",
    intelCap6Body:
      "نقاط نهاية واضحة وJSON متوقع، لتسهيل دمج Briefly في منتجاتك وسير عملك.",
    roadmapTitle: "قادم لاحقاً",
    roadmapLede: "متاح اليوم: درجات الأثر والحقول الثنائية اللغة. على الخريطة:",
    roadmapEventTitle: "اكتشاف الأحداث",
    roadmapEventBody: "تجميع الأخبار المرتبطة في أحداث سوق يمكن لمنتجك الاشتراك فيها.",
    roadmapAssetTitle: "ربط الأصول",
    roadmapAssetBody: "ربط الأخبار بالأسهم والسلع والأصول الأخرى عند إطلاق هذه الطبقة.",
    flowTitle: "من الخبر إلى بيانات يمكنك البناء عليها",
    flowLede:
      "تحوّل Briefly تطورات الأسواق إلى بيانات منظمة يمكن لمنتجاتك معالجتها والاستفادة منها.",
    flowStep1Title: "رصد",
    flowStep1Body:
      "نجمع وننظم التطورات والأخبار ذات الصلة بالأسواق عبر مختلف الموضوعات المالية والاقتصادية.",
    flowStep2Title: "تنظيم",
    flowStep2Body: "نحوّل الأخبار إلى بيانات واضحة ومنظمة، مع السياق والبيانات الوصفية التي تحتاجها تطبيقاتك.",
    flowStep3Title: "تقييم",
    flowStep3Body: "نحلل الأخبار وفق مؤشرات مرتبطة بالسوق للمساعدة في تحديد أهميتها وتأثيرها المحتمل.",
    flowStep4Title: "توصيل",
    flowStep4Body:
      "احصل على بيانات السوق المنظمة من خلال API بسيطة، جاهزة للتطبيقات ولوحات المعلومات وأدوات البحث وسير العمل المعتمد على الذكاء الاصطناعي.",
    flowCloser: "واجهة API واحدة. ذكاء سوقي منظم. مصمم لما هو قادم.",
    impactTitle: "قيّم كل خبر بحسب السوق.",
    impactLede: "كل خبر يحمل درجة أثر على الفائدة والنفط والمعادن والدولار. رتّب الموجز حسب ما يحرّك السوق، لا حسب الأحدث فقط.",
    capsTitle: "خصائص الواجهة التي تستخدمها المكاتب",
    capIntegrateTitle: "REST وترويسة واحدة",
    capIntegrateBody: "أرسل X-API-Key واستدعِ /api/v1/market-news. مستكشف اللوحة جزء من المنتج.",
    capCountriesTitle: "أكثر من 100 دولة",
    capCountriesBody: "صفِّ بأكواد ISO مثل US وAE وGB وDE وFR. التغطية من الكتالوج، لا من عدد مصادر مبالغ فيه.",
    capRegionsTitle: "ثلاث مناطق سوق",
    capRegionsBody: "middle_east وamerica وglobal. استخدم region عندما يفكر المكتب بالكتل لا بالدول فقط.",
    capJsonTitle: "JSON بلغتين",
    capJsonBody: "title وsummary يتبعان طلبك. arabic وenglish يبقيان في الخبر نفسه، مع الدولة والفئة والدرجات.",
    capLangTitle: "العربية أولاً",
    capLangBody: "العربية هي الافتراضية. اطلب الإنجليزية عند الحاجة. اللغتان تبقيان في كل خبر.",
    capFreeTitle: "جرّب على المجاني",
    capFreeBody: "أنشئ حساب لوحة، أنشئ مفتاح API، وابق ضمن الحد اليومي. اطلب Pro مقابل 70 دولاراً شهرياً من الفوترة.",
    queryTitle: "ابحث وصفِّ كما تعمل الواجهة",
    queryLede: "المعاملات أدناه هي سلسلة الاستعلام الحقيقية. لا عوامل مخترعة.",
    queryTabSearch: "كلمات",
    queryTabRegion: "المنطقة",
    queryTabPublishers: "المصادر والفئات",
    queryTabTime: "الزمن",
    querySearch1: "q يبحث بالعربية أو الإنجليزية. مثال: أسعار النفط أو oil prices.",
    querySearch2: "searchIn يقيّد q بالعنوان أو الملخص أو كليهما.",
    querySearch3: "لا يوجد بناء OR منطقي. استخدم q ثم ضيّق بـ country أو category أو nationality.",
    querySearchCode: "q=oil&searchIn=title&sort=score",
    queryRegion1: "country يأخذ أكواد ISO مفصولة بفاصلة. مثال: US,AE.",
    queryRegion2: "region هي middle_east أو america أو global.",
    queryRegion3: "nationality يشكّل إحاطات مجتمعية لجمهور، لا دولة المقال.",
    queryRegionCode: "country=US,AE&region=global",
    queryPub1: "category رمز من الكتالوج مثل finance أو oil أو commodities أو markets.",
    queryPub2: "source رمز مصدر، مفصول بفاصلة.",
    queryPub3: "اجمع source مع category عندما يحتاج المكتب نطاقاً أضيق من الموجز نفسه.",
    queryPubCode: "category=oil&sort=score",
    queryTime1: "بدون تواريخ تستخدم البيانات نافذة حداثة 72 ساعة.",
    queryTime2: "date يوم تقويم واحد ويتجاوز تلك النافذة.",
    queryTime3: "from وto حدود تاريخ نشر شاملة لاستعلام الأرشيف.",
    queryTimeCode: "from=2026-08-01&to=2026-08-21&sort=date",
    sourcesTitle: "ما تعيده الواجهة",
    sourcesLede:
      "أخبار أسواق منظّمة للمنتجات: حقول ثنائية اللغة، فلاتر دولة وفئة، وموجز مباشر مع أرشيف.",
    sourcesRss: "استجابات منظمة",
    sourcesGnews: "حقول ثنائية اللغة",
    sourcesCatalog: "كتالوج الدول",
    sourcesConsole: "مفاتيح اللوحة والمستكشف",
    coverageTitle: "من سوق واحد إلى العالم",
    coverageLede: "صفِّ حسب الدولة أو حسب فئة السوق.",
    coverageCta: "افتح الموجز",
    coverageStatApi: "1",
    coverageStatApiHint: "واجهة API",
    coverageRegionLabel: "مناطق سوق",
    coverageCatLabel: "فئات رئيسية",
    regionsMapTitle: "التغطية حسب المنطقة",
    regionsMapLede: "الشرق الأوسط، الأمريكتان، والأسواق العالمية. كل بطاقة تعرض دولاً من ذلك النطاق.",
    regionMore: "أخرى",
    regionCountHint: "دولة",
    bilingualTitle: "عربية وإنجليزية في كل خبر",
    bilingualLede:
      "كل خبر يصل بعنوان وملخص بالعربية وبالإنجليزية. title وsummary يتبعان لغة طلبك. العربية هي الافتراضية.",
    bilingualArTitle: "العربية",
    bilingualArBody: "arabic.title وarabic.summary هما العنوان والملخص بالعربية.",
    bilingualEnTitle: "الإنجليزية",
    bilingualEnBody: "english.title وenglish.summary هما العنوان والملخص بالإنجليزية.",
    useCasesTitle: "لمن هذا الموجز",
    useCasesLede: "ادمج أخبار الأسواق داخل منتجك: منصات تداول، تطبيقات إعلام، وكلاء ذكاء اصطناعي، وأدوات بحث.",
    useCaseFintech: "التقنية المالية والتداول",
    useCaseFintechBody: "ضع أخبار الأسواق ودرجات الأثر داخل المنصة التي يستخدمها مكتبك.",
    useCaseMedia: "الإعلام",
    useCaseMediaBody: "قدّم موجزات أسواق عالمية داخل تطبيقك، دون إنشاء غرفة أخبار.",
    useCaseAgents: "الذكاء الاصطناعي",
    useCaseAgentsBody: "امنح الوكلاء سياقاً منظماً عن الأسواق بدل نتائج بحث غير منظمة.",
    useCaseApps: "البحث والتحليل",
    useCaseAppsBody: "استعلم في أرشيف دائم من الأخبار المصنفة والقابلة للبحث.",
    useCaseQuery: "عيّنة استعلام",
    trustTitle: "تغطية جاهزة للاستعلام",
    trustLede:
      "أكثر من 100 دولة. العربية والإنجليزية في كل خبر. صفِّ حسب السوق واسترجع ما يحتاجه منتجك.",
    trustPill: "دولة",
    trustCard1:
      "أخبار أسواق حية عبر أكثر من 100 دولة، بالعربية والإنجليزية في كل خبر.",
    trustTryTitle: "جرّب الواجهة",
    trustCard2: "أنشئ مفتاح API واستكشف البيانات مباشرة من لوحة المطوّر.",
    trustQueryHint: "استعلام سوق مرتّب حسب الأثر",
    trustQueryRun: "استعلم",
    metricCountries: "دولة",
    metricLanguages: "لغات",
    metricLanguagesValue: "2",
    metricWindow: "نافذة الموجز المباشر",
    metricWindowValue: "72 ساعة",
    pricingTitle: "ابدأ مجاناً. وتوسّع عندما ينمو منتجك.",
    pricingLede: "ابدأ مجاناً لاختبار الواجهة. اختر Pro للاستخدام التجاري، أو Enterprise بسعر 150 دولاراً شهرياً.",
    planFree: "مجاني",
    planFreePrice: "$0",
    planFreeBody: "جرّب الواجهة باستجابات ثنائية اللغة ولوحة مطوّر وحد يومي للطلبات.",
    planPro: "Pro",
    planProPrice: "$70",
    planProPeriod: "/ شهر",
    planProBody: "حدود استخدام للإنتاج وفلاتر كاملة واستخدام تجاري. اطلبها من الفوترة.",
    planEnterprise: "Enterprise",
    planEnterprisePrice: "150 دولاراً",
    planEnterpriseBody: "حدود حجم أعلى ودعم أولوية واتفاقية مستوى خدمة منشورة. اطلبها من الفوترة. المجاني وPro بلا SLA منشور.",
    planCtaStart: "ابدأ مجاناً",
    planCtaContact: "تواصل معنا",
    skipToContent: "انتقل إلى المحتوى",
    navAria: "التنقل الرئيسي",
    langAria: "اللغة",
    menuOpen: "القائمة",
    menuClose: "إغلاق",
    footerHome: "الرئيسية",
    faqTitle: "أسئلة شائعة",
    faqWhatQ: "ما هو Briefly NewsStream؟",
    faqWhatA:
      "واجهة ذكاء أسواق للمنتجات. لكل خبر حقول ثنائية اللغة ودرجات أثر يمكن تصفيتها وترتيبها.",
    faqWhereQ: "ما المناطق والدول التي تغطيها؟",
    faqWhereA:
      "صفِّ حسب الدولة أو المنطقة عبر الشرق الأوسط والخليج وأوروبا والأمريكتين والأسواق العالمية. صفحة التغطية تعرض القائمة كاملة.",
    faqLangQ: "هل العربية فعلاً بمستوى أول؟",
    faqLangA:
      "نعم. العربية هي الافتراضية. title وsummary يتبعان lang. arabic وenglish يبقيان في كل خبر.",
    faqImpactQ: "ما تقييم أثر السوق؟",
    faqImpactA:
      "كل خبر يأتي بدرجة أثر على الفائدة والنفط والمعادن والدولار. رتّب الموجز حسب التأثير عندما لا يكفي الأحدث أولاً.",
    faqArchiveQ: "هل تحذفون المقالات التاريخية؟",
    faqArchiveA:
      "Supabase الحي يحتفظ بنحو 5 أيام للموجز (حدود الخطة المجانية). أرشيف Cloudflare R2 اختياري للتاريخ الأطول عبر /archive — docs/R2-CLOUDFLARE-SETUP.md.",
    faqKeyQ: "كيف أبدأ؟",
    faqKeyA:
      "سجّل في لوحة المطوّر، أنشئ مفتاح API، ثم استدعِ نقاط النهاية أو جرّب المستكشف. الخطة المجانية متاحة للتجربة.",
    faqPayQ: "كيف أترقى إلى Pro؟",
    faqPayA: "أنشئ حساباً وابدأ بالخطة المجانية، ثم اطلب Pro من الفوترة. الدفع غير مفعّل في اللوحة بعد.",
    finalTitle: "احصل على مفتاح مجاني واستدعِ الموجز.",
    finalLede: "أنشئ مفتاحك من لوحة التحكم وابدأ بالخطة المجانية، واطلب Pro مقابل 70 دولاراً شهرياً من الفوترة.",
    footerProduct: "المنتج",
    footerDocs: "توثيق API",
    footerConsole: "اللوحة",
    footerNews: "الموجز",
    footerArchive: "الأرشيف",
    archiveKicker: "التاريخ",
    archiveTitle: "أرشيف أخبار الأسواق",
    archiveLede:
      "تخزين بارد اختياري (Cloudflare R2) لما بعد نافذة Supabase الحية (5 أيام). الموجز يعمل بدونه حتى تُفعّله.",
    archiveNotConfigured: "تخزين الأرشيف غير مُعد بعد.",
    archiveEmpty: "لا توجد أيام مؤرشفة بعد. سيظهر هنا أول تشغيل للأرشفة.",
    archiveDayCount: (count: number) => `${count} قصة`,
    archiveBackLive: "العودة إلى الموجز الحي",
    archiveDayTitle: (date: string) => `الأرشيف · ${date}`,
    archiveDayLede: (count: number) => `${count} قصة مؤرشفة لهذا اليوم.`,
    archiveEmptyDay: "لا قصص مؤرشفة لهذا اليوم.",
    archiveBackIndex: "كل أيام الأرشيف",
    footerDevelopers: "للمطوّرين",
    footerResources: "موارد",
    footerLlms: "llms.txt",
    footerCompany: "الشركة",
    footerContact: "تواصل",
    footerLegal: "قانوني",
    footerPrivacy: "الخصوصية",
    footerTerms: "الشروط",
    footerRights: "واجهة ذكاء أسواق للمطوّرين والمنتجات الرقمية.",
    footerCopyright: "© 2026 Briefly NewsStream",
    footerMetaAria: "قانوني والحساب",
    notFoundTitle: "الصفحة غير موجودة",
    notFoundLede: "هذا المسار غير موجود على المنصة. استخدم القائمة أو ابحث في الموجز أو ارجع إلى الرئيسية.",
    notFoundHome: "العودة إلى الرئيسية",
  },
} as const;

export function marketingCopy(lang: MarketingLang) {
  return copy[lang];
}
