import type { MarketingLang } from "@/lib/marketing-copy";

const en = {
  pageTitle: "Market news API plans",
  pageLede:
    "Start free to try the API. Choose Pro for commercial use, or contact us for a custom Enterprise plan.",
  forFree: "Try the news API, create an API key, and stay within the daily limit.",
  forPro: "Ship on one API, with production usage limits and commercial use.",
  forEnterprise: "Custom pricing for volume, support, and an SLA.",
  periodMonth: "/ month",
  customPrice: "Custom pricing",
  meterRequests: "API requests",
  meterKeys: "API keys",
  meterLicense: "License",
  meterSla: "SLA",
  requestsUnit: "/ day",
  licenseEval: "Evaluation",
  licenseCommercial: "Commercial",
  slaNone: "None published",
  slaScoped: "Set to your needs",
  meterHint: "The daily limit renews automatically every day.",
  featureFree1: "Console, API keys, and explorer",
  featureFree2: "Arabic and English JSON on every news endpoint",
  featureFree3: "The same filters as Pro, within the Free limit",
  featureFree4: "Not licensed for commercial production",
  featurePro1: "20,000 requests a day",
  featurePro2: "Commercial use of the API",
  featurePro3: "Market briefings and advanced time filters",
  featurePro4: "Request Pro from Billing at $70 a month",
  featureEnt1: "200,000 requests a day by default, adjustable",
  featureEnt2: "Up to 100 API keys",
  featureEnt3: "Support and an SLA set to your needs",
  featureEnt4: "Free and Pro have no published SLA",
  includedTitle: "Core features on every plan",
  includedLede: "Same API, same data shape. Usage limits change with the plan.",
  included1Title: "Arabic and English fields",
  included1Body: "Arabic-first responses with a complete English twin.",
  included2Title: "Coverage across 70+ countries",
  included2Body: "Filter by country and market using ISO codes.",
  included3Title: "7 core categories",
  included3Body: "Gold, finance, economics, oil, Middle East economy, commodities, and markets.",
  included4Title: "Story impact score",
  included4Body: "Rank news by likely market impact, not recency alone.",
  included5Title: "Historical archive",
  included5Body:
    "Keep access to indexed news and query it when you need it. The default query window is 72 hours.",
  included6Title: "Developer console",
  included6Body: "Create API keys, review usage, and try the explorer.",
  startTitle: "Send your first request in minutes",
  startLede: "Create your account, create an API key, then get your first market news response from the API.",
  startStep1: "Create your account",
  startStep2: "Create an API key",
  startStep3: "Send a request to /api/v1/market-news",
  compareHref: "Full plan details",
  ctaStart: "Start free",
  ctaPro: "Start with Pro",
  ctaEnterprise: "Contact us",
  faqTitle: "Plan questions",
  faqRequestQ: "What counts as an API request?",
  faqRequestA:
    "Each news request counts toward your daily limit.",
  faqResetQ: "When does the daily limit renew?",
  faqResetA: "The daily limit renews automatically every day.",
  faqFreeQ: "Can I use the Free plan in a commercial product?",
  faqFreeA:
    "Free is for evaluation. Commercial use starts on Pro. The endpoints are the same. The license and usage limits change.",
  faqPayQ: "How do I upgrade to Pro?",
  faqPayA:
    "Create an account, start on Free, then request Pro from Billing. Payment is not live in the console yet.",
  faqSlaQ: "Do the plans include a service level agreement (SLA)?",
  faqSlaA: "Not on Free or Pro. Enterprise can include an SLA set to your needs.",
  faqArchiveQ: "Does Free include archive access?",
  faqArchiveA:
    "Yes. Indexed articles stay in the historical archive on every plan. The default query window is 72 hours. Time filters query further back.",
  nextTitle: "Start using the news API",
  nextLede: "Create a free account, create an API key, and start testing news and data.",
  nextProof:
    "Free includes 5 API requests a day. Pro starts at $70 per month and includes 20,000 API requests a day.",
} as const;

const ar = {
  pageTitle: "خطط واجهة برمجة أخبار الأسواق",
  pageLede:
    "ابدأ مجاناً لاختبار الواجهة. اختر Pro للاستخدام التجاري، أو تواصل معنا للحصول على خطة Enterprise مخصصة.",
  forFree: "اختبر واجهة الأخبار، أنشئ مفتاح API، وابق ضمن الحد اليومي.",
  forPro: "ابنِ منتجك على واجهة برمجة واحدة، مع حدود استخدام للإنتاج واستخدام تجاري.",
  forEnterprise: "تسعير مخصص للحجم والدعم واتفاقية مستوى الخدمة.",
  periodMonth: "/ شهر",
  customPrice: "تسعير مخصص",
  meterRequests: "طلبات API",
  meterKeys: "مفاتيح API",
  meterLicense: "الترخيص",
  meterSla: "SLA",
  requestsUnit: "/ يوم",
  licenseEval: "تجربة",
  licenseCommercial: "تجاري",
  slaNone: "غير منشور",
  slaScoped: "يُحدَّد حسب احتياجاتك",
  meterHint: "الحد اليومي يتجدد تلقائياً كل يوم.",
  featureFree1: "لوحة ومفاتيح API ومستكشف",
  featureFree2: "JSON بالعربية والإنجليزية على كل نقطة أخبار",
  featureFree3: "نفس فلاتر Pro ضمن الحد اليومي للمجاني",
  featureFree4: "غير مرخّص للإنتاج التجاري",
  featurePro1: "20,000 طلب يومياً",
  featurePro2: "استخدام تجاري لواجهة برمجة التطبيقات",
  featurePro3: "إحاطات السوق وفلاتر زمنية متقدمة",
  featurePro4: "اطلب Pro من الفوترة مقابل 70 دولاراً شهرياً",
  featureEnt1: "200,000 طلب يومياً افتراضياً، قابلة للتعديل",
  featureEnt2: "حتى 100 مفتاح API",
  featureEnt3: "دعم واتفاقية مستوى خدمة تُحدَّد حسب احتياجاتك",
  featureEnt4: "المجاني وPro بلا اتفاقية مستوى خدمة منشورة",
  includedTitle: "المزايا الأساسية متاحة على جميع الخطط",
  includedLede: "نفس الواجهة، نفس بنية البيانات، مع حدود استخدام تختلف حسب الخطة.",
  included1Title: "حقول عربية وإنجليزية",
  included1Body: "استجابة بالعربية أولاً مع توأم إنجليزي كامل.",
  included2Title: "تغطية لأكثر من 70 دولة",
  included2Body: "فلترة حسب الدولة والأسواق باستخدام رموز ISO.",
  included3Title: "7 فئات رئيسية",
  included3Body: "الذهب، المالية، الاقتصاد، النفط، اقتصاد الشرق الأوسط، السلع، والأسواق.",
  included4Title: "درجة تأثير الخبر",
  included4Body: "رتّب الأخبار حسب مدى تأثيرها المحتمل على السوق، وليس حسب حداثتها فقط.",
  included5Title: "أرشيف تاريخي",
  included5Body:
    "احتفظ بالوصول إلى الأخبار المفهرسة واستعلم عنها عند الحاجة. النافذة الافتراضية للاستعلام هي 72 ساعة.",
  included6Title: "لوحة المطوّر",
  included6Body: "أنشئ مفاتيح API، راجع الاستخدام، وجرّب المستكشف.",
  startTitle: "أرسل طلبك الأول خلال دقائق",
  startLede: "أنشئ حسابك، أنشئ مفتاح API، ثم احصل على أول موجز أخبار عبر الواجهة.",
  startStep1: "أنشئ حسابك",
  startStep2: "أنشئ مفتاح API",
  startStep3: "أرسل طلباً إلى /api/v1/market-news",
  compareHref: "تفاصيل الخطط",
  ctaStart: "ابدأ مجاناً",
  ctaPro: "ابدأ مع Pro",
  ctaEnterprise: "تواصل معنا",
  faqTitle: "أسئلة الخطط",
  faqRequestQ: "ما الذي يُحتسب كطلب API؟",
  faqRequestA:
    "كل طلب أخبار يُحتسب من حدك اليومي.",
  faqResetQ: "متى يتجدد الحد اليومي؟",
  faqResetA: "يتجدد الحد اليومي تلقائياً كل يوم.",
  faqFreeQ: "هل يمكنني استخدام الخطة المجانية في منتج تجاري؟",
  faqFreeA:
    "الخطة المجانية للاختبار. الاستخدام التجاري يبدأ من Pro. نقاط النهاية واحدة. الترخيص وحدود الاستخدام يتغيران.",
  faqPayQ: "كيف يمكنني الترقية إلى Pro؟",
  faqPayA:
    "أنشئ حساباً وابدأ بالخطة المجانية، ثم اطلب Pro من الفوترة. الدفع غير مفعّل في اللوحة بعد.",
  faqSlaQ: "هل تتضمن الخطط اتفاقية مستوى خدمة (SLA)؟",
  faqSlaA: "لا على المجاني أو Pro. يمكن لـ Enterprise أن يشمل اتفاقية مستوى خدمة تُحدَّد حسب احتياجاتك.",
  faqArchiveQ: "هل يتضمن الاشتراك المجاني الوصول إلى الأرشيف؟",
  faqArchiveA:
    "نعم. المقالات المفهرسة تبقى في الأرشيف التاريخي على كل خطة. النافذة الافتراضية للاستعلام 72 ساعة. الفلاتر الزمنية تستعلم أبعد.",
  nextTitle: "ابدأ باستخدام واجهة الأخبار",
  nextLede: "أنشئ حساباً مجانياً، أنشئ مفتاح API، وابدأ باختبار الأخبار والبيانات.",
  nextProof:
    "تتضمن الخطة المجانية 5 طلبات API يومياً. تبدأ خطة Pro بسعر 70 دولاراً شهرياً وتشمل 20,000 طلب API يومياً.",
} as const;

export type PricingCopy = { [K in keyof typeof en]: string };

export function pricingCopy(lang: MarketingLang): PricingCopy {
  return lang === "en" ? en : ar;
}

export const PRICING_CONTACT = "hello@brieflynewsstream.com";
