import type { MarketingLang } from "@/lib/marketing-copy";
import { PLAN_DEFINITIONS, formatPlanCount } from "@/lib/plans";

const en = {
  pageTitle: "Market news API plans",
  planFree: "Free",
  planPro: "Pro",
  planEnterprise: "Enterprise",
  pageLede:
    "Start free to try the API. Choose Pro for commercial use, or Enterprise at $150 a month.",
  forFree: "Try the news API, create an API key, and stay within the daily limit.",
  forPro: "Ship on one API, with production usage limits and commercial use.",
  forEnterprise: "Higher volume, more keys, priority support, and a published SLA.",
  periodMonth: "/ month",
  customPrice: "Custom pricing",
  meterRequests: "API requests",
  meterKeys: "API keys",
  meterLicense: "License",
  meterSla: "SLA",
  requestsUnit: "/ day",
  licenseEval: "Evaluation",
  licenseCommercial: "Commercial",
  slaNone: "None published",
  slaScoped: "Published SLA",
  meterHint: "The daily limit renews automatically every day.",
  featureFree1: "Console, API keys, and explorer",
  featureFree2: "Arabic and English JSON on every news endpoint",
  featureFree3: "The same filters as Pro, within the Free limit",
  featureFree4: "Not licensed for commercial production",
  featureQuotaUnit: "requests a day",
  featureEntQuotaNote: "",
  featureProCommercial: "Commercial use of the API",
  featureProBilling: `Request Pro from Billing at $${PLAN_DEFINITIONS.PRO.listPriceMonthlyUsd} a month`,
  featureEntKeysPrefix: "Up to ",
  featureEntKeysSuffix: " API keys",
  featureEntSla: "Priority support and a published SLA",
  featureEntCustom: "Request Enterprise from Billing at $150 a month",
  includedTitle: "Core features on every plan",
  includedLede: "Same API, same data shape. Usage limits change with the plan.",
  included1TitleEm: "Arabic and English",
  included1TitleRest: "fields",
  included1Body: "Arabic-first responses with a complete ",
  included1BodyEm: "English twin",
  included1BodyTail: ".",
  included2TitleEm: "100+ countries",
  included2TitleRest: "coverage",
  included2Body: "Filter by country and market using ",
  included2BodyEm: "ISO codes",
  included2BodyTail: ".",
  included3TitleEm: "7 core categories",
  included3TitleRest: "",
  included3Body: "Finance, economics, oil, commodities, markets, and precious metals.",
  included3BodyEm: "",
  included3BodyTail: "",
  included4TitleEm: "Impact score",
  included4TitleRest: "ranking",
  included4Body: "Rank news by likely ",
  included4BodyEm: "market impact",
  included4BodyTail: ", not recency alone.",
  included5TitleEm: "72-hour archive",
  included5TitleRest: "access",
  included5Body: "Indexed news stays queryable. Default live window: ",
  included5BodyEm: "72 hours",
  included5BodyTail: ".",
  included6TitleEm: "Developer console",
  included6TitleRest: "",
  included6Body: "Create ",
  included6BodyEm: "API keys",
  included6BodyTail: ", review usage, and try the explorer.",
  startTitle: "Send your first request in minutes",
  startLede: "Create your account, create an API key, then get your first market news response from the API.",
  startStep1: "Create your account",
  startStep2: "Create an API key",
  startStep3: "Send a request to /api/v1/market-news",
  compareHref: "Full plan details",
  ctaStart: "Start free",
  ctaPro: "Subscribe to Pro",
  ctaEnterprise: "Subscribe to Enterprise",
  faqTitle: "Plan questions",
  faqRequestQ: "What counts as an API request?",
  faqRequestA:
    "Every authenticated API request counts toward your daily limit, including catalog and source endpoints. Health does not.",
  faqResetQ: "When does the daily limit renew?",
  faqResetA: "The daily limit renews automatically every day.",
  faqFreeQ: "Can I use the Free plan in a commercial product?",
  faqFreeA:
    "Free is for evaluation. Commercial use starts on Pro. The endpoints are the same. The license and usage limits change.",
  faqPayQ: "How do I upgrade?",
  faqPayA:
    `Create an account, start on Free, then request Pro ($${PLAN_DEFINITIONS.PRO.listPriceMonthlyUsd}) or Enterprise ($${PLAN_DEFINITIONS.ENTERPRISE.listPriceMonthlyUsd}) from Billing and pay by card checkout.`,
  faqSlaQ: "Do the plans include a service level agreement (SLA)?",
  faqSlaA: "Not on Free or Pro. Enterprise includes a published SLA.",
  faqArchiveQ: "Does Free include archive access?",
  faqArchiveA:
    "Yes. Indexed articles stay in the historical archive on every plan. The default query window is 72 hours. Time filters query further back.",
  nextTitle: "Start using the news API",
  nextLede: "Create a free account, create an API key, and start testing news and data.",
  nextProof:
    `Free includes ${PLAN_DEFINITIONS.FREE.dailyRequests} API requests a day. Pro is $${PLAN_DEFINITIONS.PRO.listPriceMonthlyUsd} per month with ${formatPlanCount(PLAN_DEFINITIONS.PRO.dailyRequests)} requests a day. Enterprise is $${PLAN_DEFINITIONS.ENTERPRISE.listPriceMonthlyUsd} per month with ${formatPlanCount(PLAN_DEFINITIONS.ENTERPRISE.dailyRequests)} requests a day.`,
} as const;

const ar = {
  pageTitle: "خطط واجهة برمجة أخبار الأسواق",
  planFree: "مجاني",
  planPro: "Pro",
  planEnterprise: "Enterprise",
  pageLede:
    "ابدأ مجاناً لاختبار الواجهة. اختر Pro للاستخدام التجاري، أو Enterprise بسعر 150 دولاراً شهرياً.",
  forFree: "اختبر واجهة الأخبار، أنشئ مفتاح API، وابق ضمن الحد اليومي.",
  forPro: "ابنِ منتجك على واجهة برمجة واحدة، مع حدود استخدام للإنتاج واستخدام تجاري.",
  forEnterprise: "حجم أعلى، مفاتيح أكثر، دعم أولوية، واتفاقية مستوى خدمة منشورة.",
  periodMonth: "/ شهر",
  customPrice: "تسعير مخصص",
  meterRequests: "طلبات API",
  meterKeys: "مفاتيح API",
  meterLicense: "الترخيص",
  meterSla: "SLA",
  requestsUnit: "/ يوم",
  licenseEval: "تجربة",
  licenseCommercial: "تجاري",
  slaNone: "غير منشور",
  slaScoped: "SLA منشور",
  meterHint: "الحد اليومي يتجدد تلقائياً كل يوم.",
  featureFree1: "لوحة ومفاتيح API ومستكشف",
  featureFree2: "JSON بالعربية والإنجليزية على كل نقطة أخبار",
  featureFree3: "نفس فلاتر Pro ضمن الحد اليومي للمجاني",
  featureFree4: "غير مرخّص للإنتاج التجاري",
  featureQuotaUnit: "طلب يومياً",
  featureEntQuotaNote: "",
  featureProCommercial: "استخدام تجاري لواجهة برمجة التطبيقات",
  featureProBilling: `اطلب Pro من الفوترة مقابل ${PLAN_DEFINITIONS.PRO.listPriceMonthlyUsd} دولاراً شهرياً`,
  featureEntKeysPrefix: "حتى ",
  featureEntKeysSuffix: " مفاتيح API",
  featureEntSla: "دعم أولوية واتفاقية مستوى خدمة منشورة",
  featureEntCustom: "اطلب Enterprise من الفوترة مقابل 150 دولاراً شهرياً",
  includedTitle: "المزايا الأساسية متاحة على جميع الخطط",
  includedLede: "نفس الواجهة، نفس بنية البيانات، مع حدود استخدام تختلف حسب الخطة.",
  included1TitleEm: "عربية وإنجليزية",
  included1TitleRest: "حقول",
  included1Body: "استجابة بالعربية أولاً مع ",
  included1BodyEm: "توأم إنجليزي كامل",
  included1BodyTail: ".",
  included2TitleEm: "100+ دولة",
  included2TitleRest: "تغطية",
  included2Body: "فلترة حسب الدولة والأسواق باستخدام ",
  included2BodyEm: "رموز ISO",
  included2BodyTail: ".",
  included3TitleEm: "7 فئات رئيسية",
  included3TitleRest: "",
  included3Body: "المالية، الاقتصاد، النفط، السلع، الأسواق، والمعادن الثمينة.",
  included3BodyEm: "",
  included3BodyTail: "",
  included4TitleEm: "درجة التأثير",
  included4TitleRest: "ترتيب",
  included4Body: "رتّب الأخبار حسب ",
  included4BodyEm: "تأثيرها على السوق",
  included4BodyTail: "، وليس حسب حداثتها فقط.",
  included5TitleEm: "أرشيف 72 ساعة",
  included5TitleRest: "",
  included5Body: "الأخبار المفهرسة تبقى قابلة للاستعلام. النافذة الافتراضية: ",
  included5BodyEm: "72 ساعة",
  included5BodyTail: ".",
  included6TitleEm: "لوحة المطوّر",
  included6TitleRest: "",
  included6Body: "أنشئ ",
  included6BodyEm: "مفاتيح API",
  included6BodyTail: "، راجع الاستخدام، وجرّب المستكشف.",
  startTitle: "أرسل طلبك الأول خلال دقائق",
  startLede: "أنشئ حسابك، أنشئ مفتاح API، ثم احصل على أول موجز أخبار عبر الواجهة.",
  startStep1: "أنشئ حسابك",
  startStep2: "أنشئ مفتاح API",
  startStep3: "أرسل طلباً إلى /api/v1/market-news",
  compareHref: "تفاصيل الخطط",
  ctaStart: "ابدأ مجاناً",
  ctaPro: "اشترك في Pro",
  ctaEnterprise: "اشترك في Enterprise",
  faqTitle: "أسئلة الخطط",
  faqRequestQ: "ما الذي يُحتسب كطلب API؟",
  faqRequestA:
    "كل طلب API موثّق يُحتسب من حدك اليومي، بما في ذلك مسارات الكتالوج والمصادر. طلب الحالة الصحية لا يُحتسب.",
  faqResetQ: "متى يتجدد الحد اليومي؟",
  faqResetA: "يتجدد الحد اليومي تلقائياً كل يوم.",
  faqFreeQ: "هل يمكنني استخدام الخطة المجانية في منتج تجاري؟",
  faqFreeA:
    "الخطة المجانية للاختبار. الاستخدام التجاري يبدأ من Pro. نقاط النهاية واحدة. الترخيص وحدود الاستخدام يتغيران.",
  faqPayQ: "كيف يمكنني الترقية؟",
  faqPayA:
    `أنشئ حساباً وابدأ بالخطة المجانية، ثم اطلب Pro (${PLAN_DEFINITIONS.PRO.listPriceMonthlyUsd} دولاراً) أو Enterprise (${PLAN_DEFINITIONS.ENTERPRISE.listPriceMonthlyUsd} دولاراً) من الفوترة وادفع عبر صفحة الدفع بالبطاقة.`,
  faqSlaQ: "هل تتضمن الخطط اتفاقية مستوى خدمة (SLA)؟",
  faqSlaA: "لا على المجاني أو Pro. تتضمن Enterprise اتفاقية مستوى خدمة منشورة.",
  faqArchiveQ: "هل يتضمن الاشتراك المجاني الوصول إلى الأرشيف؟",
  faqArchiveA:
    "نعم. المقالات المفهرسة تبقى في الأرشيف التاريخي على كل خطة. النافذة الافتراضية للاستعلام 72 ساعة. الفلاتر الزمنية تستعلم أبعد.",
  nextTitle: "ابدأ باستخدام واجهة الأخبار",
  nextLede: "أنشئ حساباً مجانياً، أنشئ مفتاح API، وابدأ باختبار الأخبار والبيانات.",
  nextProof:
    `تتضمن الخطة المجانية ${PLAN_DEFINITIONS.FREE.dailyRequests} طلبات API يومياً. خطة Pro بسعر ${PLAN_DEFINITIONS.PRO.listPriceMonthlyUsd} دولاراً شهرياً وتشمل ${formatPlanCount(PLAN_DEFINITIONS.PRO.dailyRequests)} طلب API يومياً. خطة Enterprise بسعر ${PLAN_DEFINITIONS.ENTERPRISE.listPriceMonthlyUsd} دولاراً شهرياً وتشمل ${formatPlanCount(PLAN_DEFINITIONS.ENTERPRISE.dailyRequests)} طلب API يومياً.`,
} as const;

export type PricingCopy = { [K in keyof typeof en]: string };

export function pricingCopy(lang: MarketingLang): PricingCopy {
  return lang === "en" ? en : ar;
}

export const PRICING_CONTACT = "hello@brieflynewsstream.com";
