-- AlterTable
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "country" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "address" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "mobilePhone" TEXT NOT NULL DEFAULT '';
