import { Category } from "@prisma/client";
import { arabicPublisherRss } from "./types";

/** Native Arabic RSS — no Gemini translation required. */
export const ARABIC_NATIVE_PUBLISHERS = [
  // Kuwait desk (focused)
  arabicPublisherRss(
    "AR_KUNA_KW",
    "KUNA Arabic",
    "https://www.kuna.net.kw/ArticleFeed.aspx?language=ar",
    "https://www.kuna.net.kw/",
    "KW",
    Category.ME_ECONOMY,
    96,
  ),
  arabicPublisherRss(
    "AR_ALRAI_KW",
    "Al Rai Kuwait",
    "https://www.alraimedia.com/rss/feed/rss.xml",
    "https://www.alraimedia.com/",
    "KW",
    Category.ME_ECONOMY,
    88,
  ),
  arabicPublisherRss(
    "AR_ALANBA_KW",
    "Al Anba Kuwait",
    "https://www.alanba.com.kw/rss",
    "https://www.alanba.com.kw/",
    "KW",
    Category.ME_ECONOMY,
    86,
  ),
  arabicPublisherRss(
    "AR_ALJARIDA_KW",
    "Al Jarida Kuwait",
    "https://www.aljarida.com/rss",
    "https://www.aljarida.com/",
    "KW",
    Category.ME_ECONOMY,
    84,
  ),
  arabicPublisherRss(
    "AR_ALQABAS_KW",
    "Al Qabas Kuwait",
    "https://alqabas.com/rss",
    "https://alqabas.com/",
    "KW",
    Category.ME_ECONOMY,
    87,
  ),
  arabicPublisherRss(
    "AR_SEYASSAH_KW",
    "Al Seyassah Kuwait",
    "https://www.seyassah.com/rss",
    "https://www.seyassah.com/",
    "KW",
    Category.ME_ECONOMY,
    82,
  ),

  // Gulf wires (Arabic)
  arabicPublisherRss(
    "AR_SPA_SA",
    "Saudi Press Agency",
    "https://www.spa.gov.sa/rss",
    "https://www.spa.gov.sa/",
    "SA",
    Category.ME_ECONOMY,
    90,
  ),
  arabicPublisherRss(
    "AR_WAM_AE",
    "WAM UAE",
    "https://www.wam.ae/rss",
    "https://www.wam.ae/",
    "AE",
    Category.ME_ECONOMY,
    88,
  ),
  arabicPublisherRss(
    "AR_QNA_QA",
    "Qatar News Agency",
    "https://www.qna.org.qa/ar/rss",
    "https://www.qna.org.qa/",
    "QA",
    Category.ME_ECONOMY,
    86,
  ),
  arabicPublisherRss(
    "AR_BNA_BH",
    "Bahrain News Agency",
    "https://www.bna.bh/rss",
    "https://www.bna.bh/",
    "BH",
    Category.ME_ECONOMY,
    82,
  ),
  arabicPublisherRss(
    "AR_ONA_OM",
    "Oman News Agency",
    "https://omannews.gov.om/rss",
    "https://omannews.gov.om/",
    "OM",
    Category.ME_ECONOMY,
    82,
  ),
  arabicPublisherRss(
    "AR_ARGAAM_SA",
    "Argaam Saudi Finance",
    "https://www.argaam.com/ar/rss/allnews",
    "https://www.argaam.com/",
    "SA",
    Category.MARKETS,
    90,
  ),
  arabicPublisherRss(
    "AR_EQTISADIAH_SA",
    "Al Eqtisadiah Saudi",
    "https://www.aleqt.com/rss",
    "https://www.aleqt.com/",
    "SA",
    Category.FINANCE,
    88,
  ),
  arabicPublisherRss(
    "AR_OKAZ_SA",
    "Okaz Saudi",
    "https://www.okaz.com.sa/rss/all.xml",
    "https://www.okaz.com.sa/",
    "SA",
    Category.ME_ECONOMY,
    84,
  ),

  // Egypt / Levant / North Africa native Arabic
  arabicPublisherRss(
    "AR_MASRY_EG",
    "Al Masry Al Youm Egypt",
    "https://www.almasryalyoum.com/rss/rssfeeds",
    "https://www.almasryalyoum.com/",
    "EG",
    Category.ME_ECONOMY,
    88,
  ),
  arabicPublisherRss(
    "AR_MASRY_ECON_EG",
    "Al Masry Al Youm Economy",
    "https://www.almasryalyoum.com/rss/rssfeeds?sectionId=7",
    "https://www.almasryalyoum.com/",
    "EG",
    Category.ECONOMICS,
    90,
  ),
  arabicPublisherRss(
    "AR_MASRY_BUSINESS_EG",
    "Al Masry Al Youm Business",
    "https://www.almasryalyoum.com/rss/rssfeeds?sectionId=4",
    "https://www.almasryalyoum.com/",
    "EG",
    Category.FINANCE,
    88,
  ),
  arabicPublisherRss(
    "AR_YOUM7_ECON_EG",
    "Youm7 Economy Egypt",
    "https://www.youm7.com/rss/SectionRss?SectionID=297",
    "https://www.youm7.com/",
    "EG",
    Category.ECONOMICS,
    90,
  ),
  arabicPublisherRss(
    "AR_YOUM7_REPORTS_EG",
    "Youm7 Egypt Reports",
    "https://www.youm7.com/rss/SectionRss?SectionID=97",
    "https://www.youm7.com/",
    "EG",
    Category.ME_ECONOMY,
    86,
  ),
  arabicPublisherRss(
    "AR_YOUM7_ARAB_EG",
    "Youm7 Arab News",
    "https://www.youm7.com/rss/SectionRss?SectionID=88",
    "https://www.youm7.com/",
    "EG",
    Category.ME_ECONOMY,
    84,
  ),
  arabicPublisherRss(
    "AR_ANNAHAR_LB",
    "An-Nahar Lebanon",
    "https://www.annahar.com/rss",
    "https://www.annahar.com/",
    "LB",
    Category.ME_ECONOMY,
    88,
  ),
  arabicPublisherRss(
    "AR_ALMODON_LB",
    "Al Modon Lebanon",
    "https://www.almodon.com/rss",
    "https://www.almodon.com/",
    "LB",
    Category.ME_ECONOMY,
    84,
  ),
  arabicPublisherRss(
    "AR_NNA_LB",
    "NNA Lebanon Arabic",
    "https://www.nna-leb.gov.lb/ar/rss",
    "https://www.nna-leb.gov.lb/",
    "LB",
    Category.ME_ECONOMY,
    86,
  ),
  arabicPublisherRss(
    "AR_HESPRESS_MA",
    "Hespress Morocco",
    "https://www.hespress.com/feed",
    "https://www.hespress.com/",
    "MA",
    Category.ME_ECONOMY,
    86,
  ),
  arabicPublisherRss(
    "AR_ELKHABAR_DZ",
    "El Khabar Algeria",
    "https://www.elkhabar.com/feed/",
    "https://www.elkhabar.com/",
    "DZ",
    Category.ME_ECONOMY,
    84,
  ),

  // Pan-Arab business wires
  arabicPublisherRss(
    "AR_CNBC_AR",
    "CNBC Arabia",
    "https://www.cnbcarabia.com/rss",
    "https://www.cnbcarabia.com/",
    "GLOBAL",
    Category.MARKETS,
    92,
  ),
  arabicPublisherRss(
    "AR_ASHARQ_BIZ",
    "Asharq Business",
    "https://asharqbusiness.com/rss",
    "https://asharqbusiness.com/",
    "GLOBAL",
    Category.FINANCE,
    91,
  ),
  arabicPublisherRss(
    "AR_AAWSAT",
    "Asharq Al-Awsat Arabic",
    "https://www.aawsat.com/feed",
    "https://www.aawsat.com/",
    "GLOBAL",
    Category.ME_ECONOMY,
    90,
  ),
  arabicPublisherRss(
    "AR_INDEPENDENT_AR",
    "Independent Arabia",
    "https://www.independentarabia.com/rss.xml",
    "https://www.independentarabia.com/",
    "GLOBAL",
    Category.ME_ECONOMY,
    86,
  ),
  arabicPublisherRss(
    "AR_ALQUDS_AR",
    "Al-Quds Al-Arabi",
    "https://www.alquds.co.uk/feed/",
    "https://www.alquds.co.uk/",
    "GLOBAL",
    Category.ME_ECONOMY,
    84,
  ),
  arabicPublisherRss(
    "AR_CNN_AR",
    "CNN Arabic",
    "https://arabic.cnn.com/rss",
    "https://arabic.cnn.com/",
    "GLOBAL",
    Category.ECONOMICS,
    88,
  ),
  arabicPublisherRss(
    "AR_ALJAZ_ECON",
    "Al Jazeera Economy",
    "https://www.aljazeera.net/aljazeera/arc/outboundfeeds/rss/category/economy/index.xml",
    "https://www.aljazeera.net/",
    "GLOBAL",
    Category.ECONOMICS,
    90,
  ),
  arabicPublisherRss(
    "AR_ALJAZ_ALL",
    "Al Jazeera Arabic",
    "https://www.aljazeera.net/xml/rss/all.xml",
    "https://www.aljazeera.net/",
    "GLOBAL",
    Category.ECONOMICS,
    85,
  ),
  arabicPublisherRss(
    "AR_SKY_AR",
    "Sky News Arabia",
    "https://www.skynewsarabia.com/rss",
    "https://www.skynewsarabia.com/",
    "GLOBAL",
    Category.ECONOMICS,
    84,
  ),
  arabicPublisherRss(
    "AR_SKY_BIZ_AR",
    "Sky News Arabia Business",
    "https://www.skynewsarabia.com/rss/business.xml",
    "https://www.skynewsarabia.com/",
    "GLOBAL",
    Category.FINANCE,
    88,
  ),
  arabicPublisherRss(
    "AR_MUBASHER",
    "Mubasher Markets Arabic",
    "https://www.mubasher.info/rss/news",
    "https://www.mubasher.info/",
    "GLOBAL",
    Category.MARKETS,
    88,
  ),
  arabicPublisherRss(
    "AR_INVESTING_SA",
    "Investing.com Arabic",
    "https://sa.investing.com/rss/news.rss",
    "https://sa.investing.com/",
    "GLOBAL",
    Category.MARKETS,
    87,
  ),
  arabicPublisherRss(
    "AR_INVESTING_CRYPTO",
    "Investing.com Arabic Crypto",
    "https://sa.investing.com/rss/news_301.rss",
    "https://sa.investing.com/crypto/",
    "GLOBAL",
    Category.CRYPTO,
    86,
  ),

  // Crypto / blockchain Arabic
  arabicPublisherRss(
    "AR_COINTELEGRAPH",
    "Cointelegraph Arabic",
    "https://ar.cointelegraph.com/rss",
    "https://ar.cointelegraph.com/",
    "GLOBAL",
    Category.CRYPTO,
    90,
  ),
  arabicPublisherRss(
    "AR_BEINCRYPTO",
    "BeInCrypto Arabic",
    "https://ar.beincrypto.com/feed/",
    "https://ar.beincrypto.com/",
    "GLOBAL",
    Category.CRYPTO,
    86,
  ),

  // International Arabic desks
  arabicPublisherRss(
    "AR_BBC_AR",
    "BBC Arabic",
    "https://feeds.bbci.co.uk/arabic/rss.xml",
    "https://www.bbc.com/arabic",
    "GLOBAL",
    Category.ECONOMICS,
    82,
  ),
  arabicPublisherRss(
    "AR_BBC_BIZ_AR",
    "BBC Arabic Business",
    "https://feeds.bbci.co.uk/arabic/business/rss.xml",
    "https://www.bbc.com/arabic/business",
    "GLOBAL",
    Category.FINANCE,
    88,
  ),
  arabicPublisherRss(
    "AR_FRANCE24_AR",
    "France 24 Arabic",
    "https://www.france24.com/ar/rss",
    "https://www.france24.com/ar/",
    "EU",
    Category.ECONOMICS,
    80,
  ),
  arabicPublisherRss(
    "AR_FRANCE24_ECON_AR",
    "France 24 Arabic Economy",
    "https://www.france24.com/ar/%D8%A7%D9%82%D8%AA%D8%B5%D8%A7%D8%AF/rss",
    "https://www.france24.com/ar/",
    "EU",
    Category.ECONOMICS,
    84,
  ),
  arabicPublisherRss(
    "AR_EURONEWS_AR",
    "Euronews Arabic",
    "https://arabic.euronews.com/rss",
    "https://arabic.euronews.com/",
    "EU",
    Category.ECONOMICS,
    80,
  ),
  arabicPublisherRss(
    "AR_EURONEWS_BIZ_AR",
    "Euronews Arabic Business",
    "https://arabic.euronews.com/rss?level=theme&name=business",
    "https://arabic.euronews.com/",
    "EU",
    Category.FINANCE,
    84,
  ),
  arabicPublisherRss(
    "AR_DW_AR",
    "Deutsche Welle Arabic",
    "https://rss.dw.com/rdf/rss-ar-all",
    "https://www.dw.com/ar/",
    "EU",
    Category.ECONOMICS,
    78,
  ),
  arabicPublisherRss(
    "AR_DW_BIZ_AR",
    "Deutsche Welle Arabic Business",
    "https://rss.dw.com/xml/rss-ar-bus",
    "https://www.dw.com/ar/",
    "EU",
    Category.FINANCE,
    82,
  ),
  arabicPublisherRss(
    "AR_RT_AR",
    "RT Arabic",
    "https://arabic.rt.com/rss/",
    "https://arabic.rt.com/",
    "GLOBAL",
    Category.ECONOMICS,
    72,
  ),
  arabicPublisherRss(
    "AR_ARABNEWS_SA",
    "Arab News Arabic",
    "https://www.arabnews.com/arabic/rss.xml",
    "https://www.arabnews.com/arabic",
    "SA",
    Category.ME_ECONOMY,
    84,
  ),
  arabicPublisherRss(
    "AR_ELMUNDO_AR",
    "Al Arabiya Business Arabic",
    "https://www.alarabiya.net/.rss/ar/business.xml",
    "https://www.alarabiya.net/ar/business",
    "GLOBAL",
    Category.FINANCE,
    86,
  ),
  arabicPublisherRss(
    "AR_ELMUNDO_TECH",
    "Al Arabiya Technology Arabic",
    "https://www.alarabiya.net/.rss/ar/technology.xml",
    "https://www.alarabiya.net/ar/technology",
    "GLOBAL",
    Category.TECH,
    82,
  ),
] as const;
