import { Category } from "@prisma/client";
import { type CountrySourceSeed, type PublisherRow, rowsToSources } from "./types";

/**
 * Global / official / wire RSS. URLs are public feeds (not HTML scrapers).
 * Core seed already owns Fed press/monetary/speeches, ECB press, BBC Business,
 * MarketWatch top stories, CNBC Markets, Al Jazeera all, Reuters/Bloomberg sitemaps.
 */
const GLOBAL_ROWS = [
  // US official
  ["FED_BCREG", "Federal Reserve Banking", "https://www.federalreserve.gov/feeds/press_bcreg.xml", "https://www.federalreserve.gov/newsevents.htm", "US", Category.ECONOMICS, 98],
  ["FED_ENFORCEMENT", "Federal Reserve Enforcement", "https://www.federalreserve.gov/feeds/press_enforcement.xml", "https://www.federalreserve.gov/newsevents.htm", "US", Category.ECONOMICS, 96],
  ["FED_OTHER", "Federal Reserve Other Press", "https://www.federalreserve.gov/feeds/press_other.xml", "https://www.federalreserve.gov/newsevents.htm", "US", Category.ECONOMICS, 96],
  ["FED_TESTIMONY", "Federal Reserve Testimony", "https://www.federalreserve.gov/feeds/testimony.xml", "https://www.federalreserve.gov/newsevents/testimony.htm", "US", Category.ECONOMICS, 98],
  ["NY_FED", "New York Fed", "https://www.newyorkfed.org/rss", "https://www.newyorkfed.org/", "US", Category.ECONOMICS, 96],
  ["STLOUIS_FED_BLOG", "FRED Blog", "https://fredblog.stlouisfed.org/feed/", "https://fredblog.stlouisfed.org/", "US", Category.ECONOMICS, 92],
  ["ATLANTA_FED_MACRO", "Atlanta Fed Macroblog", "https://www.atlantafed.org/rss/macroblog", "https://www.atlantafed.org/", "US", Category.ECONOMICS, 90],
  ["CFTC_PRESS", "CFTC Press", "https://www.cftc.gov/RSS/RSS.xml", "https://www.cftc.gov/", "US", Category.MARKETS, 94],
  ["SEC_PRESS", "SEC Press", "https://www.sec.gov/news/pressreleases.rss", "https://www.sec.gov/news/pressreleases", "US", Category.FINANCE, 96],
  ["BLS_NEWS", "US Bureau of Labor Statistics", "https://www.bls.gov/feed/bls_latest.rss", "https://www.bls.gov/", "US", Category.ECONOMICS, 98],
  ["BEA_NEWS", "Bureau of Economic Analysis", "https://www.bea.gov/rss.xml", "https://www.bea.gov/", "US", Category.ECONOMICS, 98],
  ["EIA_TODAY", "EIA Today in Energy", "https://www.eia.gov/rss/todayinenergy.xml", "https://www.eia.gov/todayinenergy/", "US", Category.OIL, 95],
  ["EIA_PRESS", "EIA Press", "https://www.eia.gov/rss/press_feed.xml", "https://www.eia.gov/", "US", Category.OIL, 95],
  ["WHITEHOUSE_BRIEFING", "White House Briefing Room", "https://www.whitehouse.gov/briefing-room/feed/", "https://www.whitehouse.gov/briefing-room/", "US", Category.ECONOMICS, 90],

  // ECB / EU official
  ["ECB_BLOG", "ECB Blog", "https://www.ecb.europa.eu/rss/blog.html", "https://www.ecb.europa.eu/press/blog/html/index.en.html", "EU", Category.ECONOMICS, 96],
  ["ECB_STATS", "ECB Statistical Press", "https://www.ecb.europa.eu/rss/statpress.html", "https://www.ecb.europa.eu/press/pr/stats/html/index.en.html", "EU", Category.ECONOMICS, 98],
  ["ECB_INTERVIEWS", "ECB Interviews", "https://www.ecb.europa.eu/rss/inter.html", "https://www.ecb.europa.eu/press/inter/html/index.en.html", "EU", Category.ECONOMICS, 95],
  ["ECB_PAPERS", "ECB Working Papers", "https://www.ecb.europa.eu/rss/wppub.html", "https://www.ecb.europa.eu/pub/economic-research/working-papers/html/index.en.html", "EU", Category.ECONOMICS, 92],
  ["EC_PRESS", "European Commission Press", "https://ec.europa.eu/commission/presscorner/api/rss?dotcmsid=all&language=en", "https://ec.europa.eu/commission/presscorner/home/en", "EU", Category.ECONOMICS, 94],

  // International institutions
  ["IMF_NEWS", "IMF News", "https://www.imf.org/en/News/rss", "https://www.imf.org/en/News", "GLOBAL", Category.ECONOMICS, 98],
  ["WORLD_BANK_NEWS", "World Bank News", "https://www.worldbank.org/en/news/all/rss", "https://www.worldbank.org/en/news", "GLOBAL", Category.ECONOMICS, 96],
  ["OECD_NEWS", "OECD Newsroom", "https://www.oecd.org/newsroom/rss.xml", "https://www.oecd.org/newsroom/", "GLOBAL", Category.ECONOMICS, 95],
  ["BIS_PRESS", "BIS Press", "https://www.bis.org/doclist/all_pressrels.rss", "https://www.bis.org/press/", "GLOBAL", Category.ECONOMICS, 98],
  ["BIS_SPEECHES", "BIS Speeches", "https://www.bis.org/doclist/speeches.rss", "https://www.bis.org/speeches/", "GLOBAL", Category.ECONOMICS, 96],
  ["WTO_NEWS", "WTO News", "https://www.wto.org/library/rss/latest_news_e.xml", "https://www.wto.org/english/news_e/news_e.htm", "GLOBAL", Category.ECONOMICS, 94],
  ["UN_ECONOMIC", "UN Economic Development", "https://news.un.org/feed/subscribe/en/news/topic/economic-development/feed/rss.xml", "https://news.un.org/en/news/topic/economic-development", "GLOBAL", Category.ECONOMICS, 90],
  ["IEA_NEWS", "International Energy Agency", "https://www.iea.org/feeds/news.rss", "https://www.iea.org/news", "GLOBAL", Category.OIL, 94],
  ["OPEC_PRESS", "OPEC Press", "https://www.opec.org/opec_web/static_files_project/media/rss/press_releases.xml", "https://www.opec.org/", "GLOBAL", Category.OIL, 94],

  // UK official / BBC extra
  ["BOE_NEWS", "Bank of England News", "https://www.bankofengland.co.uk/rss/news", "https://www.bankofengland.co.uk/news", "GB", Category.ECONOMICS, 100],
  ["BOE_PUBLICATIONS", "Bank of England Publications", "https://www.bankofengland.co.uk/rss/publications", "https://www.bankofengland.co.uk/news", "GB", Category.ECONOMICS, 96],
  ["BOE_SPEECHES", "Bank of England Speeches", "https://www.bankofengland.co.uk/rss/speeches", "https://www.bankofengland.co.uk/news", "GB", Category.ECONOMICS, 97],
  ["BBC_WORLD", "BBC World", "https://feeds.bbci.co.uk/news/world/rss.xml", "https://www.bbc.com/news/world", "GB", Category.MARKETS, 90],
  ["BBC_UK", "BBC UK", "https://feeds.bbci.co.uk/news/uk/rss.xml", "https://www.bbc.com/news/uk", "GB", Category.MARKETS, 86],
  ["BBC_POLITICS", "BBC Politics", "https://feeds.bbci.co.uk/news/politics/rss.xml", "https://www.bbc.com/news/politics", "GB", Category.ECONOMICS, 84],
  ["BBC_SCIENCE", "BBC Science Environment", "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml", "https://www.bbc.com/news/science_and_environment", "GB", Category.COMMODITIES, 78],
  ["SKY_BUSINESS", "Sky News Business", "https://feeds.skynews.com/feeds/rss/business.xml", "https://news.sky.com/business", "GB", Category.FINANCE, 84],
  ["SKY_WORLD", "Sky News World", "https://feeds.skynews.com/feeds/rss/world.xml", "https://news.sky.com/world", "GB", Category.MARKETS, 82],
  ["GUARDIAN_BUSINESS", "The Guardian Business", "https://www.theguardian.com/uk/business/rss", "https://www.theguardian.com/uk/business", "GB", Category.FINANCE, 88],
  ["GUARDIAN_ECONOMICS", "The Guardian Economics", "https://www.theguardian.com/business/economics/rss", "https://www.theguardian.com/business/economics", "GB", Category.ECONOMICS, 88],
  ["GUARDIAN_US_BUSINESS", "The Guardian US Business", "https://www.theguardian.com/us/business/rss", "https://www.theguardian.com/us/business", "US", Category.FINANCE, 86],
  ["INDEPENDENT_UK_BUSINESS", "The Independent Business", "https://www.independent.co.uk/news/business/rss", "https://www.independent.co.uk/news/business", "GB", Category.FINANCE, 82],
  ["CITY_AM", "City AM", "https://www.cityam.com/feed/", "https://www.cityam.com/", "GB", Category.FINANCE, 82],
  ["FT_HOME", "Financial Times Home", "https://www.ft.com/rss/home", "https://www.ft.com/", "GB", Category.FINANCE, 94],
  ["FT_MARKETS", "Financial Times Markets", "https://www.ft.com/markets?format=rss", "https://www.ft.com/markets", "GB", Category.FINANCE, 94],
  ["FT_WORLD", "Financial Times World", "https://www.ft.com/world?format=rss", "https://www.ft.com/world", "GLOBAL", Category.MARKETS, 92],

  // US wires / business press
  ["NYT_BUSINESS", "NYTimes Business", "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml", "https://www.nytimes.com/section/business", "US", Category.FINANCE, 92],
  ["NYT_ECONOMY", "NYTimes Economy", "https://rss.nytimes.com/services/xml/rss/nyt/Economy.xml", "https://www.nytimes.com/section/business/economy", "US", Category.ECONOMICS, 92],
  ["NYT_DEALBOOK", "NYTimes DealBook", "https://rss.nytimes.com/services/xml/rss/nyt/Dealbook.xml", "https://www.nytimes.com/section/business/dealbook", "US", Category.FINANCE, 90],
  ["NYT_ENERGY", "NYTimes Energy Environment", "https://rss.nytimes.com/services/xml/rss/nyt/EnergyEnvironment.xml", "https://www.nytimes.com/section/business/energy-environment", "US", Category.OIL, 86],
  ["WSJ_WORLD", "WSJ World News", "https://feeds.a.dj.com/rss/RSSWorldNews.xml", "https://www.wsj.com/news/world", "GLOBAL", Category.MARKETS, 94],
  ["WSJ_MARKETS", "WSJ Markets", "https://feeds.a.dj.com/rss/RSSMarketsMain.xml", "https://www.wsj.com/news/markets", "US", Category.FINANCE, 95],
  ["WSJ_BUSINESS", "WSJ US Business", "https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml", "https://www.wsj.com/news/business", "US", Category.FINANCE, 94],
  ["NPR_BUSINESS", "NPR Business", "https://feeds.npr.org/1006/rss.xml", "https://www.npr.org/sections/business/", "US", Category.FINANCE, 88],
  ["NPR_ECONOMY", "NPR Economy", "https://feeds.npr.org/1017/rss.xml", "https://www.npr.org/sections/economy/", "US", Category.ECONOMICS, 88],
  ["CNBC_TOP", "CNBC Top News", "https://www.cnbc.com/id/100003114/device/rss/rss.html", "https://www.cnbc.com/", "US", Category.MARKETS, 88],
  ["CNBC_WORLD", "CNBC World", "https://www.cnbc.com/id/100727362/device/rss/rss.html", "https://www.cnbc.com/world/", "GLOBAL", Category.MARKETS, 88],
  ["CNBC_ECONOMY", "CNBC Economy", "https://www.cnbc.com/id/20910258/device/rss/rss.html", "https://www.cnbc.com/economy/", "US", Category.ECONOMICS, 90],
  ["CNBC_FINANCE", "CNBC Finance", "https://www.cnbc.com/id/10000664/device/rss/rss.html", "https://www.cnbc.com/finance/", "US", Category.FINANCE, 88],
  ["CNBC_EARNINGS", "CNBC Earnings", "https://www.cnbc.com/id/15839135/device/rss/rss.html", "https://www.cnbc.com/earnings/", "US", Category.FINANCE, 86],
  ["CNBC_ENERGY", "CNBC Energy", "https://www.cnbc.com/id/19836768/device/rss/rss.html", "https://www.cnbc.com/energy/", "US", Category.OIL, 86],
  ["CNBC_ASIA", "CNBC Asia", "https://www.cnbc.com/id/10000113/device/rss/rss.html", "https://www.cnbc.com/asia-business/", "GLOBAL", Category.FINANCE, 86],
  ["CNBC_CRYPTO", "CNBC Crypto", "https://www.cnbc.com/id/44877279/device/rss/rss.html", "https://www.cnbc.com/cryptoworld/", "US", Category.FINANCE, 84],
  ["MARKETWATCH_PULSE", "MarketWatch Pulse", "https://feeds.marketwatch.com/marketwatch/marketpulse/", "https://www.marketwatch.com/", "US", Category.FINANCE, 86],
  ["MARKETWATCH_REALTIME", "MarketWatch Realtime", "https://feeds.marketwatch.com/marketwatch/realtimeheadlines/", "https://www.marketwatch.com/", "US", Category.FINANCE, 86],
  ["YAHOO_FINANCE", "Yahoo Finance News", "https://finance.yahoo.com/news/rssindex", "https://finance.yahoo.com/news/", "US", Category.FINANCE, 84],
  ["CNN_MONEY", "CNN Money Latest", "http://rss.cnn.com/rss/money_latest.rss", "https://www.cnn.com/business", "US", Category.FINANCE, 84],
  ["CNN_ECONOMY", "CNN Money Economy", "http://rss.cnn.com/rss/money_news_economy.rss", "https://www.cnn.com/business", "US", Category.ECONOMICS, 84],
  ["CNN_MARKETS", "CNN Money Markets", "http://rss.cnn.com/rss/money_markets.rss", "https://www.cnn.com/business/markets", "US", Category.FINANCE, 84],
  ["FORTUNE", "Fortune", "https://fortune.com/feed/", "https://fortune.com/", "US", Category.FINANCE, 84],
  ["BUSINESS_INSIDER", "Business Insider", "https://www.businessinsider.com/rss", "https://www.businessinsider.com/", "US", Category.FINANCE, 80],
  ["SEEKING_ALPHA", "Seeking Alpha Market Currents", "https://seekingalpha.com/market_currents.xml", "https://seekingalpha.com/", "US", Category.FINANCE, 80],
  ["WASHPOST_BUSINESS", "Washington Post Business", "https://feeds.washingtonpost.com/rss/business", "https://www.washingtonpost.com/business/", "US", Category.FINANCE, 88],
  ["POLITICO_ECONOMY", "Politico Economy", "https://rss.politico.com/economy.xml", "https://www.politico.com/economy", "US", Category.ECONOMICS, 82],
  ["HILL_BUSINESS", "The Hill Finance", "https://thehill.com/business/feed/", "https://thehill.com/business/", "US", Category.ECONOMICS, 76],

  // Wires / international
  ["FRANCE24_EN", "France 24 English", "https://www.france24.com/en/rss", "https://www.france24.com/en/", "FR", Category.MARKETS, 86],
  ["FRANCE24_BUSINESS", "France 24 Business", "https://www.france24.com/en/business/rss", "https://www.france24.com/en/business/", "FR", Category.FINANCE, 86],
  ["FRANCE24_ECO", "France 24 Economy", "https://www.france24.com/en/economy/rss", "https://www.france24.com/en/economy/", "FR", Category.ECONOMICS, 86],
  ["RFI_EN", "RFI English", "https://www.rfi.fr/en/rss", "https://www.rfi.fr/en/", "FR", Category.MARKETS, 82],
  ["DW_ALL", "Deutsche Welle English", "https://rss.dw.com/rdf/rss-en-all", "https://www.dw.com/en/", "DE", Category.MARKETS, 86],
  ["DW_ECONOMY", "Deutsche Welle Economy", "https://rss.dw.com/xml/rss-en-eco", "https://www.dw.com/en/economy/s-12776", "DE", Category.ECONOMICS, 86],
  ["REUTERS_AGENCY_BIZ", "Reuters Agency Business", "https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best", "https://www.reutersagency.com/", "GLOBAL", Category.FINANCE, 94],
  ["REUTERS_AGENCY_ECON", "Reuters Agency Economy", "https://www.reutersagency.com/feed/?best-topics=economy&post_type=best", "https://www.reutersagency.com/", "GLOBAL", Category.ECONOMICS, 94],

  // Commodities / mining / energy
  ["OILPRICE", "OilPrice", "https://oilprice.com/rss/main", "https://oilprice.com/", "GLOBAL", Category.OIL, 88],
  ["MINING_COM", "Mining.com", "https://www.mining.com/feed/", "https://www.mining.com/", "GLOBAL", Category.COMMODITIES, 88],
  ["BULLIONVAULT", "BullionVault News", "https://www.bullionvault.com/gold-news/rss", "https://www.bullionvault.com/gold-news", "GLOBAL", Category.GOLD, 84],
  ["RIGZONE", "Rigzone", "https://www.rigzone.com/news/rss.asp", "https://www.rigzone.com/news/", "GLOBAL", Category.OIL, 80],

  // Asia official / English
  ["BOJ_WHATSNEW", "Bank of Japan", "https://www.boj.or.jp/en/rss/whatsnew.xml", "https://www.boj.or.jp/en/", "JP", Category.ECONOMICS, 100],
  ["CHINA_DAILY_BIZ", "China Daily Business", "https://www.chinadaily.com.cn/rss/business_rss.xml", "https://www.chinadaily.com.cn/business", "CN", Category.FINANCE, 82],
  ["CHINA_DAILY_CHINA", "China Daily China", "https://www.chinadaily.com.cn/rss/china_rss.xml", "https://www.chinadaily.com.cn/", "CN", Category.MARKETS, 80],
  ["XINHUA_EN", "Xinhua English World", "https://www.xinhuanet.com/english/rss/worldrss.xml", "https://english.news.cn/", "CN", Category.MARKETS, 80],
  ["CAIXIN_GLOBAL", "Caixin Global", "https://www.caixinglobal.com/feed/", "https://www.caixinglobal.com/", "CN", Category.FINANCE, 86],
  ["NIKKEI_ASIA", "Nikkei Asia", "https://asia.nikkei.com/rss/feed/nar", "https://asia.nikkei.com/", "JP", Category.FINANCE, 90],
  ["NHK_WORLD", "NHK World", "https://www3.nhk.or.jp/nhkworld/en/news/rss/", "https://www3.nhk.or.jp/nhkworld/", "JP", Category.MARKETS, 86],

  // Canada / Australia / others extra
  ["CBC_BUSINESS", "CBC Business", "https://www.cbc.ca/webfeed/rss/rss-business", "https://www.cbc.ca/news/business", "CA", Category.FINANCE, 86],
  ["GLOBE_MAIL_BIZ", "Globe and Mail Business", "https://www.theglobeandmail.com/arc/outboundfeeds/rss/category/business/", "https://www.theglobeandmail.com/business/", "CA", Category.FINANCE, 86],
  ["BOC_PRESS", "Bank of Canada Press", "https://www.bankofcanada.ca/press/feed/", "https://www.bankofcanada.ca/", "CA", Category.ECONOMICS, 98],
  ["RBA_MEDIA", "Reserve Bank of Australia", "https://www.rba.gov.au/rss/rss-cb-media-releases.xml", "https://www.rba.gov.au/media-releases/", "AU", Category.ECONOMICS, 100],
  ["RBNZ_NEWS", "Reserve Bank of New Zealand", "https://www.rbnz.govt.nz/feeds/news", "https://www.rbnz.govt.nz/", "NZ", Category.ECONOMICS, 98],

  // Extra global English business
  ["MIDDLE_EAST_EYE", "Middle East Eye", "https://www.middleeasteye.net/rss", "https://www.middleeasteye.net/", "GLOBAL", Category.ME_ECONOMY, 78],
  ["MEI_NEWS", "Middle East Institute", "https://www.mei.edu/feed", "https://www.mei.edu/", "GLOBAL", Category.ME_ECONOMY, 76],
  ["ATLANTIC_COUNCIL", "Atlantic Council", "https://www.atlanticcouncil.org/feed/", "https://www.atlanticcouncil.org/", "GLOBAL", Category.ECONOMICS, 76],
  ["BROOKINGS", "Brookings", "https://www.brookings.edu/feed/", "https://www.brookings.edu/", "US", Category.ECONOMICS, 82],
  ["PIIE", "Peterson Institute", "https://www.piie.com/rss.xml", "https://www.piie.com/", "US", Category.ECONOMICS, 86],
  ["VOXEU", "VoxEU", "https://cepr.org/voxeu/rss.xml", "https://cepr.org/voxeu", "EU", Category.ECONOMICS, 84],
  ["PROJECT_SYNDICATE", "Project Syndicate", "https://www.project-syndicate.org/rss", "https://www.project-syndicate.org/", "GLOBAL", Category.ECONOMICS, 80],
] as const;

const GUARDIAN_SECTION_ROWS = [
  ["AFRICA", "Africa", "world/africa", Category.MARKETS, 86],
  ["AMERICAS", "Americas", "world/americas", Category.MARKETS, 84],
  ["ASIA_PACIFIC", "Asia Pacific", "world/asia-pacific", Category.MARKETS, 86],
  ["AUSTRALIA_NEWS", "Australia News", "australia-news", Category.MARKETS, 84],
  ["BANKING", "Banking", "business/banking", Category.FINANCE, 86],
  ["BUSINESS_LIVE", "Business Live", "business/live", Category.FINANCE, 86],
  ["CENTRAL_BANKS", "Central Banks", "business/central-banks", Category.ECONOMICS, 86],
  ["CHINA", "China", "world/china", Category.MARKETS, 86],
  ["COMMODITIES", "Commodities", "business/commodities", Category.COMMODITIES, 86],
  ["EUROPE_NEWS", "Europe News", "world/europe-news", Category.MARKETS, 86],
  ["EUROZONE", "Eurozone", "business/eurozone", Category.ECONOMICS, 86],
  ["FINANCIAL_SECTOR", "Financial Sector", "business/financial-sector", Category.FINANCE, 86],
  ["FTSE", "FTSE", "business/ftse", Category.FINANCE, 84],
  ["GLOBAL_ECONOMY", "Global Economy", "business/global-economy", Category.ECONOMICS, 88],
  ["INDIA", "India", "world/india", Category.MARKETS, 84],
  ["INFLATION", "Inflation", "business/inflation", Category.ECONOMICS, 86],
  ["INTEREST_RATES", "Interest Rates", "business/interestrates", Category.ECONOMICS, 86],
  ["MIDDLE_EAST", "Middle East", "world/middleeast", Category.ME_ECONOMY, 86],
  ["OIL", "Oil", "business/oil", Category.OIL, 86],
  ["RETAIL", "Retail", "business/retail", Category.FINANCE, 82],
  ["STOCK_MARKETS", "Stock Markets", "business/stock-markets", Category.FINANCE, 86],
  ["TECHNOLOGY", "Technology", "technology", Category.MARKETS, 82],
  ["TRADE_POLICY", "Trade Policy", "business/trade-policy", Category.ECONOMICS, 84],
  ["US_NEWS", "US News", "us-news", Category.MARKETS, 84],
  ["WALL_STREET", "Wall Street", "business/wallstreet", Category.FINANCE, 86],
  ["WORLD", "World", "world", Category.MARKETS, 88],
  ["WORLD_BANK", "World Bank", "business/worldbank", Category.ECONOMICS, 84],
  ["WORLD_TRADE_ORG", "World Trade Organization", "business/worldtradeorganisation", Category.ECONOMICS, 84],
] as const;

const NYT_SECTION_ROWS = [
  ["AFRICA", "Africa", "Africa", Category.MARKETS, 86],
  ["AMERICAS", "Americas", "Americas", Category.MARKETS, 84],
  ["ASIA_PACIFIC", "Asia Pacific", "AsiaPacific", Category.MARKETS, 86],
  ["AUTOMOBILES", "Automobiles", "Automobiles", Category.FINANCE, 82],
  ["EUROPE", "Europe", "Europe", Category.MARKETS, 86],
  ["GLOBAL_HOME", "Global Home", "GlobalHome", Category.MARKETS, 88],
  ["INTERNATIONAL_BUSINESS", "International Business", "InternationalBusiness", Category.FINANCE, 88],
  ["JOBS", "Jobs", "Jobs", Category.ECONOMICS, 82],
  ["MEDIA_ADVERTISING", "Media Advertising", "MediaandAdvertising", Category.FINANCE, 82],
  ["MIDDLE_EAST", "Middle East", "MiddleEast", Category.ME_ECONOMY, 86],
  ["MONEY", "Money", "YourMoney", Category.FINANCE, 84],
  ["POLITICS", "Politics", "Politics", Category.ECONOMICS, 82],
  ["SMALL_BUSINESS", "Small Business", "SmallBusiness", Category.FINANCE, 82],
  ["TECHNOLOGY", "Technology", "Technology", Category.MARKETS, 84],
  ["US", "US", "US", Category.MARKETS, 84],
  ["WORLD", "World", "World", Category.MARKETS, 90],
] as const;

const BBC_SECTION_ROWS = [
  ["AFRICA", "Africa", "world/africa", Category.MARKETS, 86],
  ["ASIA", "Asia", "world/asia", Category.MARKETS, 86],
  ["ECONOMY", "Economy", "topics/c1038wnxypvt", Category.ECONOMICS, 84],
  ["EUROPE", "Europe", "world/europe", Category.MARKETS, 86],
  ["MIDDLE_EAST", "Middle East", "world/middle_east", Category.ME_ECONOMY, 86],
  ["TECHNOLOGY", "Technology", "technology", Category.MARKETS, 82],
] as const;

const FT_SECTION_ROWS = [
  ["AFRICA", "Africa", "world/africa", Category.MARKETS, 88],
  ["ASIA_PACIFIC", "Asia Pacific", "world/asia-pacific", Category.MARKETS, 88],
  ["BANKING", "Banking", "companies/banks", Category.FINANCE, 90],
  ["CAPITAL_MARKETS", "Capital Markets", "markets/capital-markets", Category.FINANCE, 90],
  ["CENTRAL_BANKS", "Central Banks", "central-banks", Category.ECONOMICS, 90],
  ["CHINA", "China", "world/asia-pacific/china", Category.MARKETS, 88],
  ["COMMODITIES", "Commodities", "markets/commodities", Category.COMMODITIES, 90],
  ["COMPANIES", "Companies", "companies", Category.FINANCE, 90],
  ["ECONOMICS", "Economics", "economics", Category.ECONOMICS, 92],
  ["EMERGING_MARKETS", "Emerging Markets", "markets/emerging-markets", Category.FINANCE, 90],
  ["ENERGY", "Energy", "companies/energy", Category.OIL, 90],
  ["EUROPE", "Europe", "world/europe", Category.MARKETS, 88],
  ["FINANCIALS", "Financials", "companies/financials", Category.FINANCE, 90],
  ["GLOBAL_ECONOMY", "Global Economy", "global-economy", Category.ECONOMICS, 92],
  ["INDIA", "India", "world/asia-pacific/india", Category.MARKETS, 86],
  ["LEX", "Lex", "lex", Category.FINANCE, 90],
  ["MIDDLE_EAST", "Middle East", "world/mideast", Category.ME_ECONOMY, 88],
  ["MONETARY_POLICY", "Monetary Policy", "monetary-policy", Category.ECONOMICS, 90],
  ["OIL_GAS", "Oil and Gas", "companies/oil-gas", Category.OIL, 90],
  ["TECHNOLOGY", "Technology", "technology", Category.MARKETS, 88],
  ["UK", "UK", "uk", Category.MARKETS, 88],
  ["US", "US", "us", Category.MARKETS, 88],
] as const;

const AP_SECTION_ROWS = [
  ["AFRICA", "Africa", "hub/africa", Category.MARKETS, 90],
  ["ASIA_PACIFIC", "Asia Pacific", "hub/asia-pacific", Category.MARKETS, 90],
  ["BUSINESS", "Business", "hub/business", Category.FINANCE, 92],
  ["ECONOMY", "Economy", "hub/economy", Category.ECONOMICS, 90],
  ["ENERGY", "Energy", "hub/energy", Category.OIL, 88],
  ["FINANCIAL_MARKETS", "Financial Markets", "hub/financial-markets", Category.FINANCE, 90],
  ["MIDDLE_EAST", "Middle East", "hub/middle-east", Category.ME_ECONOMY, 90],
  ["TECHNOLOGY", "Technology", "hub/technology", Category.MARKETS, 86],
  ["US_NEWS", "US News", "hub/us-news", Category.MARKETS, 88],
  ["WORLD_NEWS", "World News", "hub/world-news", Category.MARKETS, 92],
] as const;

const REUTERS_AGENCY_TOPIC_ROWS = [
  ["AUTOS", "Autos", "autos", Category.FINANCE, 92],
  ["COMMODITIES_ENERGY", "Commodities Energy", "commodities-energy", Category.COMMODITIES, 92],
  ["FINANCIAL_SERVICES", "Financial Services", "financial-services", Category.FINANCE, 92],
  ["HEALTHCARE_PHARMA", "Healthcare Pharma", "healthcare-pharmaceuticals", Category.FINANCE, 88],
  ["TECHNOLOGY", "Technology", "technology", Category.MARKETS, 90],
  ["WORLD", "World", "world", Category.MARKETS, 92],
] as const;

const GUARDIAN_MARKET_COUNTRY_ROWS = [
  ["ARGENTINA", "Argentina", "world/argentina", Category.ECONOMICS, 82],
  ["AUSTRIA", "Austria", "world/austria", Category.MARKETS, 80],
  ["BAHRAIN", "Bahrain", "world/bahrain", Category.ME_ECONOMY, 78],
  ["BANGLADESH", "Bangladesh", "world/bangladesh", Category.MARKETS, 82],
  ["BELGIUM", "Belgium", "world/belgium", Category.MARKETS, 80],
  ["BRAZIL", "Brazil", "world/brazil", Category.ECONOMICS, 84],
  ["CANADA", "Canada", "world/canada", Category.MARKETS, 84],
  ["CHILE", "Chile", "world/chile", Category.ECONOMICS, 82],
  ["DENMARK", "Denmark", "world/denmark", Category.MARKETS, 80],
  ["EGYPT", "Egypt", "world/egypt", Category.ME_ECONOMY, 82],
  ["FRANCE", "France", "world/france", Category.ECONOMICS, 84],
  ["GERMANY", "Germany", "world/germany", Category.ECONOMICS, 84],
  ["GHANA", "Ghana", "world/ghana", Category.MARKETS, 80],
  ["GREECE", "Greece", "world/greece", Category.ECONOMICS, 80],
  ["INDONESIA", "Indonesia", "world/indonesia", Category.MARKETS, 82],
  ["IRAN", "Iran", "world/iran", Category.ME_ECONOMY, 80],
  ["IRAQ", "Iraq", "world/iraq", Category.ME_ECONOMY, 80],
  ["IRELAND", "Ireland", "world/ireland", Category.ECONOMICS, 82],
  ["ISRAEL", "Israel", "world/israel", Category.ME_ECONOMY, 82],
  ["ITALY", "Italy", "world/italy", Category.ECONOMICS, 84],
  ["JAPAN", "Japan", "world/japan", Category.MARKETS, 84],
  ["JORDAN", "Jordan", "world/jordan", Category.ME_ECONOMY, 78],
  ["KENYA", "Kenya", "world/kenya", Category.MARKETS, 80],
  ["KUWAIT", "Kuwait", "world/kuwait", Category.ME_ECONOMY, 78],
  ["LEBANON", "Lebanon", "world/lebanon", Category.ME_ECONOMY, 80],
  ["MALAYSIA", "Malaysia", "world/malaysia", Category.MARKETS, 82],
  ["MEXICO", "Mexico", "world/mexico", Category.ECONOMICS, 84],
  ["MOROCCO", "Morocco", "world/morocco", Category.ME_ECONOMY, 78],
  ["NETHERLANDS", "Netherlands", "world/netherlands", Category.ECONOMICS, 82],
  ["NEW_ZEALAND", "New Zealand", "world/newzealand", Category.MARKETS, 82],
  ["NIGERIA", "Nigeria", "world/nigeria", Category.MARKETS, 82],
  ["NORWAY", "Norway", "world/norway", Category.OIL, 82],
  ["OMAN", "Oman", "world/oman", Category.ME_ECONOMY, 78],
  ["PAKISTAN", "Pakistan", "world/pakistan", Category.MARKETS, 82],
  ["PHILIPPINES", "Philippines", "world/philippines", Category.MARKETS, 82],
  ["POLAND", "Poland", "world/poland", Category.ECONOMICS, 82],
  ["PORTUGAL", "Portugal", "world/portugal", Category.ECONOMICS, 80],
  ["QATAR", "Qatar", "world/qatar", Category.ME_ECONOMY, 78],
  ["SAUDI_ARABIA", "Saudi Arabia", "world/saudiarabia", Category.ME_ECONOMY, 84],
  ["SINGAPORE", "Singapore", "world/singapore", Category.FINANCE, 84],
  ["SOUTH_AFRICA", "South Africa", "world/southafrica", Category.ECONOMICS, 84],
  ["SOUTH_KOREA", "South Korea", "world/southkorea", Category.MARKETS, 84],
  ["SPAIN", "Spain", "world/spain", Category.ECONOMICS, 84],
  ["SRI_LANKA", "Sri Lanka", "world/srilanka", Category.MARKETS, 80],
  ["SWEDEN", "Sweden", "world/sweden", Category.ECONOMICS, 82],
  ["SWITZERLAND", "Switzerland", "world/switzerland", Category.FINANCE, 84],
  ["TAIWAN", "Taiwan", "world/taiwan", Category.MARKETS, 84],
  ["THAILAND", "Thailand", "world/thailand", Category.MARKETS, 82],
  ["TUNISIA", "Tunisia", "world/tunisia", Category.ME_ECONOMY, 78],
  ["TURKEY", "Turkiye", "world/turkey", Category.ECONOMICS, 82],
  ["UKRAINE", "Ukraine", "world/ukraine", Category.MARKETS, 82],
  ["UNITED_ARAB_EMIRATES", "United Arab Emirates", "world/unitedarabemirates", Category.ME_ECONOMY, 84],
  ["VIETNAM", "Vietnam", "world/vietnam", Category.MARKETS, 82],
] as const;

const GUARDIAN_BUSINESS_TOPIC_ROWS = [
  ["AIRLINES", "Airlines", "business/airline-industry", Category.FINANCE, 80],
  ["AUTOMOTIVE", "Automotive", "business/automotive-industry", Category.FINANCE, 80],
  ["BANK_OF_ENGLAND", "Bank of England", "business/bankofenglandgovernor", Category.ECONOMICS, 84],
  ["BUSINESS_TO_BUSINESS", "Business to Business", "business/business-to-business", Category.FINANCE, 78],
  ["ENERGY_COMPANIES", "Energy Companies", "business/energy-industry", Category.OIL, 84],
  ["FINANCIAL_CRISIS", "Financial Crisis", "business/financial-crisis", Category.FINANCE, 82],
  ["GLOBAL_RECESSION", "Global Recession", "business/globalrecession", Category.ECONOMICS, 82],
  ["HOUSING_MARKET", "Housing Market", "money/houseprices", Category.FINANCE, 80],
  ["INSURANCE", "Insurance", "business/insurance", Category.FINANCE, 80],
  ["MANUFACTURING", "Manufacturing", "business/manufacturing-sector", Category.ECONOMICS, 80],
  ["MINING", "Mining", "business/mining", Category.COMMODITIES, 84],
  ["MORTGAGES", "Mortgages", "money/mortgages", Category.FINANCE, 80],
  ["PENSIONS", "Pensions", "money/pensions", Category.FINANCE, 78],
  ["PHARMACEUTICALS", "Pharmaceuticals", "business/pharmaceuticals-industry", Category.FINANCE, 78],
  ["PROPERTY", "Property", "business/property", Category.FINANCE, 80],
  ["RENEWABLE_ENERGY", "Renewable Energy", "environment/renewableenergy", Category.COMMODITIES, 80],
  ["TAX_AND_SPENDING", "Tax and Spending", "politics/taxandspending", Category.ECONOMICS, 80],
  ["TRANSPORT", "Transport", "business/transport", Category.MARKETS, 78],
  ["UTILITIES", "Utilities", "business/utilities", Category.COMMODITIES, 80],
  ["WATER", "Water", "environment/water", Category.COMMODITIES, 78],
] as const;

const AP_EXTRA_HUB_ROWS = [
  ["AGRICULTURE", "Agriculture", "hub/agriculture", Category.COMMODITIES, 84],
  ["AIRLINES", "Airlines", "hub/airlines", Category.FINANCE, 82],
  ["AUTOS", "Autos", "hub/automobiles", Category.FINANCE, 82],
  ["BANKING", "Banking", "hub/banking", Category.FINANCE, 86],
  ["CHINA", "China", "hub/china", Category.MARKETS, 86],
  ["CLIMATE", "Climate", "hub/climate", Category.COMMODITIES, 82],
  ["CONSTRUCTION", "Construction", "hub/construction", Category.FINANCE, 80],
  ["CONSUMER_PRODUCTS", "Consumer Products", "hub/consumer-products-and-services", Category.FINANCE, 80],
  ["EARNINGS", "Earnings", "hub/earnings", Category.FINANCE, 84],
  ["EMPLOYMENT", "Employment", "hub/employment", Category.ECONOMICS, 84],
  ["EUROPE", "Europe", "hub/europe", Category.MARKETS, 86],
  ["FINANCE", "Finance", "hub/finance", Category.FINANCE, 86],
  ["FOOD", "Food", "hub/food", Category.COMMODITIES, 82],
  ["GAS_PRICES", "Gas Prices", "hub/gas-prices", Category.OIL, 84],
  ["GLOBAL_TRADE", "Global Trade", "hub/global-trade", Category.ECONOMICS, 84],
  ["HOUSING", "Housing", "hub/housing", Category.FINANCE, 82],
  ["INDIA", "India", "hub/india", Category.MARKETS, 84],
  ["INFLATION", "Inflation", "hub/inflation", Category.ECONOMICS, 86],
  ["MORTGAGES", "Mortgages", "hub/mortgages", Category.FINANCE, 82],
  ["OIL", "Oil", "hub/oil-and-gas", Category.OIL, 86],
  ["RETAIL", "Retail", "hub/retail", Category.FINANCE, 82],
  ["SMALL_BUSINESS", "Small Business", "hub/small-business", Category.FINANCE, 80],
  ["STOCK_MARKET", "Stock Market", "hub/stock-market", Category.FINANCE, 86],
  ["SUPPLY_CHAIN", "Supply Chain", "hub/supply-chain", Category.ECONOMICS, 82],
  ["TECH", "Tech", "hub/tech", Category.MARKETS, 84],
  ["TRADE", "Trade", "hub/trade", Category.ECONOMICS, 84],
  ["TRANSPORTATION", "Transportation", "hub/transportation", Category.MARKETS, 80],
  ["TRAVEL", "Travel", "hub/travel", Category.MARKETS, 78],
] as const;

const NYT_EXTRA_TOPIC_ROWS = [
  ["CLIMATE", "Climate", "Climate", Category.COMMODITIES, 84],
  ["EDUCATION", "Education", "Education", Category.ECONOMICS, 78],
  ["HEALTH", "Health", "Health", Category.MARKETS, 78],
  ["HOME_PAGE", "Home Page", "HomePage", Category.MARKETS, 88],
  ["PERSONAL_TECH", "Personal Tech", "PersonalTech", Category.MARKETS, 80],
  ["REAL_ESTATE", "Real Estate", "RealEstate", Category.FINANCE, 82],
  ["SCIENCE", "Science", "Science", Category.COMMODITIES, 78],
  ["THE_UPSHOT", "The Upshot", "TheUpshot", Category.ECONOMICS, 82],
  ["WASHINGTON", "Washington", "Washington", Category.ECONOMICS, 82],
] as const;

const EXTRA_GLOBAL_ROWS: PublisherRow[] = [
  ...GUARDIAN_SECTION_ROWS.map(([code, label, path, category, weight]) => [
    `GUARDIAN_${code}`,
    `The Guardian ${label}`,
    `https://www.theguardian.com/${path}/rss`,
    `https://www.theguardian.com/${path}`,
    code === "MIDDLE_EAST" ? "GLOBAL" : "GB",
    category,
    weight,
  ] as const),
  ...NYT_SECTION_ROWS.map(([code, label, feed, category, weight]) => [
    `NYT_${code}`,
    `NYTimes ${label}`,
    `https://rss.nytimes.com/services/xml/rss/nyt/${feed}.xml`,
    `https://www.nytimes.com/`,
    code === "MIDDLE_EAST" ? "GLOBAL" : "US",
    category,
    weight,
  ] as const),
  ...BBC_SECTION_ROWS.map(([code, label, path, category, weight]) => [
    `BBC_${code}`,
    `BBC ${label}`,
    `https://feeds.bbci.co.uk/news/${path}/rss.xml`,
    `https://www.bbc.com/news/${path}`,
    code === "MIDDLE_EAST" ? "GLOBAL" : "GB",
    category,
    weight,
  ] as const),
  ...FT_SECTION_ROWS.map(([code, label, path, category, weight]) => [
    `FT_${code}`,
    `Financial Times ${label}`,
    `https://www.ft.com/${path}?format=rss`,
    `https://www.ft.com/${path}`,
    code === "MIDDLE_EAST" ? "GLOBAL" : "GB",
    category,
    weight,
  ] as const),
  ...AP_SECTION_ROWS.map(([code, label, path, category, weight]) => [
    `AP_${code}`,
    `Associated Press ${label}`,
    `https://apnews.com/${path}.rss`,
    `https://apnews.com/${path}`,
    code === "MIDDLE_EAST" ? "GLOBAL" : "US",
    category,
    weight,
  ] as const),
  ...REUTERS_AGENCY_TOPIC_ROWS.map(([code, label, topic, category, weight]) => [
    `REUTERS_TOPIC_${code}`,
    `Reuters Agency ${label}`,
    `https://www.reutersagency.com/feed/?best-topics=${topic}&post_type=best`,
    "https://www.reutersagency.com/",
    "GLOBAL",
    category,
    weight,
  ] as const),
  ...GUARDIAN_MARKET_COUNTRY_ROWS.map(([code, label, path, category, weight]) => [
    `GUARDIAN_MARKET_${code}`,
    `The Guardian ${label}`,
    `https://www.theguardian.com/${path}/rss`,
    `https://www.theguardian.com/${path}`,
    "GLOBAL",
    category,
    weight,
  ] as const),
  ...GUARDIAN_BUSINESS_TOPIC_ROWS.map(([code, label, path, category, weight]) => [
    `GUARDIAN_TOPIC_${code}`,
    `The Guardian ${label}`,
    `https://www.theguardian.com/${path}/rss`,
    `https://www.theguardian.com/${path}`,
    "GB",
    category,
    weight,
  ] as const),
  ...AP_EXTRA_HUB_ROWS.map(([code, label, path, category, weight]) => [
    `AP_EXTRA_${code}`,
    `Associated Press ${label}`,
    `https://apnews.com/${path}.rss`,
    `https://apnews.com/${path}`,
    "US",
    category,
    weight,
  ] as const),
  ...NYT_EXTRA_TOPIC_ROWS.map(([code, label, feed, category, weight]) => [
    `NYT_EXTRA_${code}`,
    `NYTimes ${label}`,
    `https://rss.nytimes.com/services/xml/rss/nyt/${feed}.xml`,
    "https://www.nytimes.com/",
    "US",
    category,
    weight,
  ] as const),
  ["AL_JAZEERA_ECONOMY", "Al Jazeera Economy", "https://www.aljazeera.com/xml/rss/economy.xml", "https://www.aljazeera.com/economy/", "GLOBAL", Category.ME_ECONOMY, 88],
  ["AL_JAZEERA_MIDDLE_EAST", "Al Jazeera Middle East", "https://www.aljazeera.com/xml/rss/middle-east.xml", "https://www.aljazeera.com/middle-east/", "GLOBAL", Category.ME_ECONOMY, 88],
  ["AL_JAZEERA_BUSINESS", "Al Jazeera Business Economy", "https://www.aljazeera.com/xml/rss/tag/business-economy.xml", "https://www.aljazeera.com/tag/business-economy/", "GLOBAL", Category.ME_ECONOMY, 86],
  ["ECONOMIST_FINANCE", "The Economist Finance", "https://www.economist.com/finance-and-economics/rss.xml", "https://www.economist.com/finance-and-economics", "GB", Category.ECONOMICS, 92],
  ["ECONOMIST_BUSINESS", "The Economist Business", "https://www.economist.com/business/rss.xml", "https://www.economist.com/business", "GB", Category.FINANCE, 90],
  ["ECONOMIST_MIDDLE_EAST", "The Economist Middle East", "https://www.economist.com/middle-east-and-africa/rss.xml", "https://www.economist.com/middle-east-and-africa", "GLOBAL", Category.ME_ECONOMY, 90],
  ["NPR_WORLD", "NPR World", "https://feeds.npr.org/1004/rss.xml", "https://www.npr.org/sections/world/", "US", Category.MARKETS, 88],
  ["NPR_NATIONAL", "NPR National", "https://feeds.npr.org/1003/rss.xml", "https://www.npr.org/sections/national/", "US", Category.MARKETS, 86],
  ["NPR_TECHNOLOGY", "NPR Technology", "https://feeds.npr.org/1019/rss.xml", "https://www.npr.org/sections/technology/", "US", Category.MARKETS, 84],
  ["NPR_MIDDLE_EAST", "NPR Middle East", "https://feeds.npr.org/1009/rss.xml", "https://www.npr.org/sections/middle-east/", "GLOBAL", Category.ME_ECONOMY, 84],
  ["DW_WORLD", "Deutsche Welle World", "https://rss.dw.com/xml/rss-en-world", "https://www.dw.com/en/world/s-1429", "DE", Category.MARKETS, 86],
  ["DW_MIDDLE_EAST", "Deutsche Welle Middle East", "https://rss.dw.com/xml/rss-en-mideast", "https://www.dw.com/en/middle-east/s-14207", "GLOBAL", Category.ME_ECONOMY, 84],
  ["FRANCE24_MIDDLE_EAST", "France 24 Middle East", "https://www.france24.com/en/middle-east/rss", "https://www.france24.com/en/middle-east/", "FR", Category.ME_ECONOMY, 86],
  ["FRANCE24_AFRICA", "France 24 Africa", "https://www.france24.com/en/africa/rss", "https://www.france24.com/en/africa/", "FR", Category.MARKETS, 84],
  ["FRANCE24_ASIA", "France 24 Asia Pacific", "https://www.france24.com/en/asia-pacific/rss", "https://www.france24.com/en/asia-pacific/", "FR", Category.MARKETS, 84],
  ["RFI_MIDDLE_EAST", "RFI Middle East", "https://www.rfi.fr/en/middle-east/rss", "https://www.rfi.fr/en/middle-east/", "FR", Category.ME_ECONOMY, 82],
  ["RFI_AFRICA", "RFI Africa", "https://www.rfi.fr/en/africa/rss", "https://www.rfi.fr/en/africa/", "FR", Category.MARKETS, 82],
];

export const GLOBAL_PUBLISHERS: CountrySourceSeed[] = rowsToSources([
  ...GLOBAL_ROWS,
  ...EXTRA_GLOBAL_ROWS,
]);
